/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controler.DBManager;
import Model.Client;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gihan
 */
public class ClientSearch extends javax.swing.JFrame {

    /**
     * Creates new form ClientSearch
     */
    ManageClient ManageClient;
    NewJob newJOb;
    EditJob ManageJob;
    String frameName;

    public ClientSearch() {
        initComponents();

        getAllClientDetails();
    }

    ClientSearch(ManageClient manageClient) {
        initComponents();

        this.ManageClient = manageClient;
        frameName = manageClient.getName();
        getAllClientDetails();
    }

    ClientSearch(NewJob newJob) {
        initComponents();

        this.newJOb = newJob;
        frameName = newJob.getName();
        getAllClientDetails();
    }
    
    
     ClientSearch(EditJob manageJob) {
        initComponents();

        this.ManageJob = manageJob;
        frameName = manageJob.getName();
        getAllClientDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClient = new javax.swing.JTable();
        txtClientName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblFrameName = new javax.swing.JLabel();
        lblHeadBanner = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblClient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client Code", "Client Name", "Address", "Enter Person"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClient.setGridColor(new java.awt.Color(255, 255, 255));
        tblClient.setRowHeight(20);
        tblClient.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tblClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClient);
        if (tblClient.getColumnModel().getColumnCount() > 0) {
            tblClient.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblClient.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblClient.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 770, 180));

        txtClientName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtClientName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClientNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClientNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 560, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cliet Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, 40));

        lblFrameName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFrameName.setForeground(new java.awt.Color(255, 255, 255));
        lblFrameName.setText("Search Client");
        jPanel1.add(lblFrameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 370, 40));

        lblHeadBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main-pic.jpg"))); // NOI18N
        jPanel1.add(lblHeadBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(-470, 0, 1360, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-butn.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close-butn.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 60, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientMouseClicked

        if (evt.getClickCount() == 2) {

            processClientSearch(tblClient.getSelectedRow());

        }
    }//GEN-LAST:event_tblClientMouseClicked

    private void txtClientNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClientNameKeyReleased

        Client searchClient = new Client(txtClientName.getText());
        DBManager dbManager = new DBManager();
        ArrayList<Client> clientArray = dbManager.getClientsByClientName(searchClient);

        DefaultTableModel tblModel = (DefaultTableModel) tblClient.getModel();
        tblModel.setRowCount(0);
        for (Client client : clientArray) {
            Object columns[] = new Object[4];

            columns[0] = client.getClientCode();
            columns[1] = client.getClientName();
            columns[2] = client.getNo() + " " + client.getStreet() + " " + client.getCity();
            columns[3] = client.getRegisterPerson();
            tblModel.addRow(columns);
        }
    }//GEN-LAST:event_txtClientNameKeyReleased

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        this.dispose();
    }//GEN-LAST:event_jLabel3MousePressed

    private void txtClientNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClientNameKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tblClient.requestFocus();
        }
    }//GEN-LAST:event_txtClientNameKeyPressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed

        Client searchClient = new Client(txtClientName.getText());
        DBManager dbManager = new DBManager();
        ArrayList<Client> clientArray = dbManager.getClientsByClientName(searchClient);

        DefaultTableModel tblModel = (DefaultTableModel) tblClient.getModel();
        tblModel.setRowCount(0);
        for (Client client : clientArray) {
            Object columns[] = new Object[4];

            columns[0] = client.getClientCode();
            columns[1] = client.getClientName();
            columns[2] = client.getNo() + " " + client.getStreet() + " " + client.getCity();
            columns[3] = client.getRegisterPerson();
            tblModel.addRow(columns);
        }
    }//GEN-LAST:event_jLabel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ClientSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFrameName;
    private javax.swing.JLabel lblHeadBanner;
    private javax.swing.JTable tblClient;
    private javax.swing.JTextField txtClientName;
    // End of variables declaration//GEN-END:variables

    private void getAllClientDetails() {

        DBManager dbManager = new DBManager();
        ArrayList<Client> clientArray = dbManager.getAllClientDetails();
        DefaultTableModel tblModel = (DefaultTableModel) tblClient.getModel();

        for (Client client : clientArray) {
            Object columns[] = new Object[4];

            columns[0] = client.getClientCode();
            columns[1] = client.getClientName();
            columns[2] = client.getNo() + " " + client.getStreet() + " " + client.getCity();
            columns[3] = client.getRegisterPerson();
            tblModel.addRow(columns);
        }

    }

    private void processClientSearch(int tblRow) {

        Client client = new Client(tblClient.getValueAt(tblRow, 1).toString());

        if (frameName.equals("Manage Clent")) {

            ManageClient.searchClient(client.getClientName());

            this.dispose();
        }
        
        if (frameName.equals("New Job")) {

            newJOb.searchClientByClientName(client.getClientName());

            this.dispose();
        }
        
         if (frameName.equals("Edit Job")) {

            ManageJob.searchClientByClientName(client.getClientName());

            this.dispose();
        }
    }
}
