/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controler.DBManager.userRole;
import Controler.DBManager;
import Model.Invoice;
import Model.Job;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gihan
 */
public class CloseJob extends javax.swing.JFrame {

    /**
     * Creates new form CloseJob
     */
    Date date;
    SimpleDateFormat dateFormat;
    DefaultTableModel model;
    
    public CloseJob() {
        initComponents();
        
        date = new Date();
        dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        dcCloseDate.setDateFormatString(dateFormat.toLocalizedPattern());
        dcCloseDate.setDate(date);
        
        loadTableData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtJobID = new javax.swing.JTextField();
        lblFrameName = new javax.swing.JLabel();
        lblHeadBanner = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        lblBackButtn = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJob = new javax.swing.JTable();
        dcCloseDate = new com.toedter.calendar.JDateChooser();
        butnHome = new javax.swing.JLabel();
        lblSearchButn = new javax.swing.JLabel();
        lblHom = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblCloseJobe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Job ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, 30));
        jPanel1.add(txtJobID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 140, 30));

        lblFrameName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFrameName.setForeground(new java.awt.Color(255, 255, 255));
        lblFrameName.setText("Close Job");
        jPanel1.add(lblFrameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 370, 40));

        lblHeadBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main-pic.jpg"))); // NOI18N
        jPanel1.add(lblHeadBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, 40, 1370, 110));

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBackButtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit-butn-small.png"))); // NOI18N
        lblBackButtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBackButtnMousePressed(evt);
            }
        });
        panelHeader.add(lblBackButtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 40, 40));

        jPanel1.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 390, 20));

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDate.setText("Close Date");
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 90, 30));

        tblJob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job ID", "Company ", "Client Name", "Job Date", "Billing Month", "Sub Total", "Discount", "Net Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblJob);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 970, 210));
        jPanel1.add(dcCloseDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 150, 30));

        butnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        butnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-butn.png"))); // NOI18N
        butnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butnHomeMousePressed(evt);
            }
        });
        jPanel1.add(butnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, 70, 70));

        lblSearchButn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-butn.png"))); // NOI18N
        lblSearchButn.setText("Search");
        lblSearchButn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSearchButnMousePressed(evt);
            }
        });
        jPanel1.add(lblSearchButn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 100, 50));

        lblHom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblHom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHom.setText("Home");
        jPanel1.add(lblHom, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 530, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wave-back2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 240, 1140, 350));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 260, 20));

        lblCloseJobe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/finish-job.png"))); // NOI18N
        lblCloseJobe.setText("Close Job");
        lblCloseJobe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseJobeMousePressed(evt);
            }
        });
        jPanel1.add(lblCloseJobe, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, 110, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackButtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackButtnMousePressed
        
        this.setAlwaysOnTop(false);
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to close?", "Warning", JOptionPane.YES_NO_OPTION) == 0) {
            
            this.dispose();
        }
    }//GEN-LAST:event_lblBackButtnMousePressed

    private void butnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnHomeMousePressed
        
        this.setAlwaysOnTop(false);
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want go to home ?", "Message", JOptionPane.YES_NO_OPTION) == 0) {
            Home home = new Home(userRole);
            home.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_butnHomeMousePressed

    private void lblSearchButnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchButnMousePressed
        
        String jobID = txtJobID.getText();
        Invoice invoice = new Invoice(jobID);
        DBManager dbManager = new DBManager();
        
        invoice = dbManager.generateInvoice(invoice);
        
        model.setRowCount(0);
        
        Object row[] = new Object[8];
        row[0] = invoice.getJobId();
        row[1] = invoice.getClientName();
        row[2] = invoice.getFirstName() + " " + invoice.getLastName();
        row[3] = invoice.getJobDate();
        row[4] = invoice.getBillingMonth();
        row[5] = invoice.getSubTotal();
        row[6] = invoice.getDiscount();
        row[7] = invoice.getNetValue();
        
        model.addRow(row);
        

    }//GEN-LAST:event_lblSearchButnMousePressed

    private void lblCloseJobeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseJobeMousePressed
         String jobId = txtJobID.getText();
        String closeDate = dateFormat.format(dcCloseDate.getDate());
        int jobStatus = 0;
        
        Job job = new Job(jobId, closeDate, jobStatus);
        DBManager dbManager = new DBManager();
        boolean flag = dbManager.closeJob(job);
        
        if (flag) {
            JOptionPane.showMessageDialog(null, "Job close successfully.");
            
            loadTableData();
            
            txtJobID.setText("");
            dcCloseDate.setDate(date);
        } else {
            JOptionPane.showMessageDialog(null, "Job cancelation fail.", "Fail", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lblCloseJobeMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CloseJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CloseJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CloseJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CloseJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CloseJob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel butnHome;
    private com.toedter.calendar.JDateChooser dcCloseDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBackButtn;
    private javax.swing.JLabel lblCloseJobe;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFrameName;
    private javax.swing.JLabel lblHeadBanner;
    private javax.swing.JLabel lblHom;
    private javax.swing.JLabel lblSearchButn;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTable tblJob;
    private javax.swing.JTextField txtJobID;
    // End of variables declaration//GEN-END:variables

    private void loadTableData() {
        
        DBManager dbManager = new DBManager();
        
        ArrayList<Invoice> jobList = new ArrayList<Invoice>();
        
        jobList = dbManager.getAllActiveJobs();
        
        model = (DefaultTableModel) tblJob.getModel();
        
        model.setRowCount(0);
        
        for (int i = 0; i < jobList.size(); i++) {
            Invoice get = jobList.get(i);
            
            Object row[] = new Object[8];
            row[0] = get.getJobId();
            row[1] = get.getClientName();
            row[2] = get.getFirstName() + " " + get.getLastName();
            row[3] = get.getJobDate();
            row[4] = get.getBillingMonth();
            row[5] = get.getSubTotal();
            row[6] = get.getDiscount();
            row[7] = get.getNetValue();
            
            model.addRow(row);
            
        }
    }
}
