/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controler.DBManager.userName;
import static Controler.DBManager.userRole;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Gihan
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();

        lblUserName.setText(userName);
        lblUserType.setText(userRole);

        CurrentTime ct = new CurrentTime();
        ct.start();

    }

    public Home(String userName, String userRole) {
        initComponents();
    }

    Home(String userRole) {
        initComponents();

        lblUserName.setText(userName);
        lblUserType.setText(userRole);

        CurrentTime ct = new CurrentTime();
        ct.start();

        if (userRole.equals("Operator")) {
            buttnManageUser.setVisible(false);
            lblManageUser.setVisible(false);
            buttnReport.setVisible(false);
            lblReport.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        panelBody = new javax.swing.JPanel();
        lblDateTime = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserType = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblSystemName = new javax.swing.JLabel();
        lblWebsite = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblImg01 = new javax.swing.JLabel();
        lblBanner = new javax.swing.JLabel();
        lblImg02 = new javax.swing.JLabel();
        lblImg03 = new javax.swing.JLabel();
        lblImg04 = new javax.swing.JLabel();
        lblWave = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        buttnManageClient = new javax.swing.JLabel();
        lblManageClient = new javax.swing.JLabel();
        buttnManageStore = new javax.swing.JLabel();
        lblManageStore = new javax.swing.JLabel();
        buttnGenerateBill = new javax.swing.JLabel();
        lblGenerateBill = new javax.swing.JLabel();
        buttnReport = new javax.swing.JLabel();
        lblReport = new javax.swing.JLabel();
        buttnManageUser = new javax.swing.JLabel();
        lblManageUser = new javax.swing.JLabel();
        buttnExit = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1340, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1370, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close-button-unfill.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        panelHeader.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1335, 0, 30, 30));

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 30));

        panelBody.setBackground(new java.awt.Color(255, 255, 255));
        panelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDateTime.setFont(new java.awt.Font("Source Code Pro Black", 1, 36)); // NOI18N
        panelBody.add(lblDateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 380, 40));

        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("User Name");
        panelBody.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 30));

        lblUserType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserType.setForeground(new java.awt.Color(255, 255, 255));
        lblUserType.setText("User Type");
        panelBody.add(lblUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, 20));
        panelBody.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 310, 10));

        lblSystemName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSystemName.setForeground(new java.awt.Color(255, 255, 255));
        lblSystemName.setText("Smart Warehouse System");
        panelBody.add(lblSystemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 340, 40));

        lblWebsite.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblWebsite.setForeground(new java.awt.Color(255, 255, 255));
        lblWebsite.setText("www.smart-warehouse.com");
        panelBody.add(lblWebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 200, 20));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("info@smart-warehouse.com");
        panelBody.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 200, 20));

        lblImg01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-pic1.png"))); // NOI18N
        lblImg01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblImg01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImg01MouseExited(evt);
            }
        });
        panelBody.add(lblImg01, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 150, 140));

        lblBanner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBanner.setForeground(new java.awt.Color(255, 255, 255));
        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main-pic.jpg"))); // NOI18N
        lblBanner.setMaximumSize(new java.awt.Dimension(1370, 200));
        lblBanner.setMinimumSize(new java.awt.Dimension(1370, 200));
        lblBanner.setPreferredSize(new java.awt.Dimension(1370, 200));
        panelBody.add(lblBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 170));

        lblImg02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-pic2.png"))); // NOI18N
        lblImg02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblImg02MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImg02MouseExited(evt);
            }
        });
        panelBody.add(lblImg02, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 150, 130));

        lblImg03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-pic3.png"))); // NOI18N
        lblImg03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblImg03MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImg03MouseExited(evt);
            }
        });
        panelBody.add(lblImg03, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, 150, 140));

        lblImg04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-pic4.png"))); // NOI18N
        lblImg04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblImg04MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImg04MouseExited(evt);
            }
        });
        panelBody.add(lblImg04, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 408, 150, 130));

        lblWave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wave-pack.png"))); // NOI18N
        panelBody.add(lblWave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1370, 410));

        lblMenu.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblMenu.setText("Menu");
        panelBody.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 170, 50));
        panelBody.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 390, 10));

        buttnManageClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage-client-icon.png"))); // NOI18N
        buttnManageClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttnManageClientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttnManageClientMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttnManageClientMousePressed(evt);
            }
        });
        panelBody.add(buttnManageClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 100, 100));

        lblManageClient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblManageClient.setText("Manage Client");
        panelBody.add(lblManageClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, -1, -1));

        buttnManageStore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/store-icon.png"))); // NOI18N
        buttnManageStore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttnManageStoreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttnManageStoreMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttnManageStoreMousePressed(evt);
            }
        });
        panelBody.add(buttnManageStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 100, 100));

        lblManageStore.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblManageStore.setText("Manage Store Job");
        panelBody.add(lblManageStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 700, 130, -1));

        buttnGenerateBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill-icon.png"))); // NOI18N
        buttnGenerateBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttnGenerateBillMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttnGenerateBillMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttnGenerateBillMousePressed(evt);
            }
        });
        panelBody.add(buttnGenerateBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, 100, 100));

        lblGenerateBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGenerateBill.setText("View Invoices");
        panelBody.add(lblGenerateBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 700, 100, -1));

        buttnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report-icon.png"))); // NOI18N
        buttnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttnReportMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttnReportMousePressed(evt);
            }
        });
        panelBody.add(buttnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 590, 100, 110));

        lblReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReport.setText("Reports");
        panelBody.add(lblReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 700, 100, -1));

        buttnManageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage-user-icon.png"))); // NOI18N
        buttnManageUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttnManageUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttnManageUserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttnManageUserMousePressed(evt);
            }
        });
        panelBody.add(buttnManageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, 100, 110));

        lblManageUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblManageUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageUser.setText("Manage  User");
        panelBody.add(lblManageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 700, 100, -1));

        buttnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close-icon-big.png"))); // NOI18N
        buttnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttnExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttnExitMousePressed(evt);
            }
        });
        panelBody.add(buttnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 600, 100, 110));

        lblExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("Exit");
        panelBody.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 710, 100, -1));

        getContentPane().add(panelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1370, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblImg01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg01MouseEntered
        lblImg01.setBounds(700, 125, 150, 140);
    }//GEN-LAST:event_lblImg01MouseEntered

    private void lblImg01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg01MouseExited
        lblImg01.setBounds(700, 130, 150, 140);
    }//GEN-LAST:event_lblImg01MouseExited

    private void lblImg02MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg02MouseEntered
        lblImg02.setBounds(695, 270, 150, 130);
    }//GEN-LAST:event_lblImg02MouseEntered

    private void lblImg02MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg02MouseExited
        lblImg02.setBounds(700, 270, 150, 130);
    }//GEN-LAST:event_lblImg02MouseExited

    private void lblImg03MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg03MouseEntered
        lblImg03.setBounds(785, 270, 150, 140);
    }//GEN-LAST:event_lblImg03MouseEntered

    private void lblImg03MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg03MouseExited
        lblImg03.setBounds(780, 270, 150, 140);
    }//GEN-LAST:event_lblImg03MouseExited

    private void lblImg04MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg04MouseExited
        lblImg04.setBounds(780, 408, 150, 130);
    }//GEN-LAST:event_lblImg04MouseExited

    private void lblImg04MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg04MouseEntered
        lblImg04.setBounds(780, 410, 150, 130);
    }//GEN-LAST:event_lblImg04MouseEntered

    private void buttnManageClientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnManageClientMouseEntered
        buttnManageClient.setBounds(40, 585, 100, 100);
    }//GEN-LAST:event_buttnManageClientMouseEntered

    private void buttnManageClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnManageClientMouseExited
        buttnManageClient.setBounds(40, 590, 100, 100);
    }//GEN-LAST:event_buttnManageClientMouseExited

    private void buttnManageStoreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnManageStoreMouseEntered
        buttnManageStore.setBounds(210, 585, 100, 100);
    }//GEN-LAST:event_buttnManageStoreMouseEntered

    private void buttnManageStoreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnManageStoreMouseExited
        buttnManageStore.setBounds(210, 590, 100, 100);
    }//GEN-LAST:event_buttnManageStoreMouseExited

    private void buttnGenerateBillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnGenerateBillMouseEntered
        buttnGenerateBill.setBounds(380, 585, 100, 100);
    }//GEN-LAST:event_buttnGenerateBillMouseEntered

    private void buttnGenerateBillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnGenerateBillMouseExited
        buttnGenerateBill.setBounds(380, 590, 100, 100);
    }//GEN-LAST:event_buttnGenerateBillMouseExited

    private void buttnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnReportMouseEntered
        buttnReport.setBounds(550, 585, 100, 100);
    }//GEN-LAST:event_buttnReportMouseEntered

    private void buttnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnReportMouseExited
        buttnReport.setBounds(550, 590, 100, 100);
    }//GEN-LAST:event_buttnReportMouseExited

    private void buttnManageUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnManageUserMouseEntered
        buttnManageUser.setBounds(720, 585, 100, 100);
    }//GEN-LAST:event_buttnManageUserMouseEntered

    private void buttnManageUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnManageUserMouseExited
        buttnManageUser.setBounds(720, 590, 100, 100);
    }//GEN-LAST:event_buttnManageUserMouseExited

    private void buttnManageUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnManageUserMousePressed

        MenuUser menuUser = new MenuUser();
        menuUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttnManageUserMousePressed

    private void buttnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnExitMouseEntered

        buttnExit.setBounds(1240, 600, 100, 110);
    }//GEN-LAST:event_buttnExitMouseEntered

    private void buttnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnExitMouseExited
        buttnExit.setBounds(1240, 605, 100, 110);
    }//GEN-LAST:event_buttnExitMouseExited

    private void buttnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnExitMousePressed
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Warning", JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_buttnExitMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed

        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Warning", JOptionPane.YES_NO_OPTION) == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblCloseMousePressed

    private void buttnManageClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnManageClientMousePressed
        MenuCliet menuClient = new MenuCliet();
        menuClient.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttnManageClientMousePressed

    private void buttnManageStoreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnManageStoreMousePressed
        MenuStore menuStore = new MenuStore();
        menuStore.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttnManageStoreMousePressed

    private void buttnReportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnReportMousePressed
        MenuRepots menuReports = new MenuRepots();
        menuReports.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttnReportMousePressed

    private void buttnGenerateBillMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnGenerateBillMousePressed
        ViewAllJobs viewJobs = new ViewAllJobs();
        viewJobs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttnGenerateBillMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttnExit;
    private javax.swing.JLabel buttnGenerateBill;
    private javax.swing.JLabel buttnManageClient;
    private javax.swing.JLabel buttnManageStore;
    private javax.swing.JLabel buttnManageUser;
    private javax.swing.JLabel buttnReport;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGenerateBill;
    private javax.swing.JLabel lblImg01;
    private javax.swing.JLabel lblImg02;
    private javax.swing.JLabel lblImg03;
    private javax.swing.JLabel lblImg04;
    private javax.swing.JLabel lblManageClient;
    private javax.swing.JLabel lblManageStore;
    private javax.swing.JLabel lblManageUser;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblSystemName;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JLabel lblWave;
    private javax.swing.JLabel lblWebsite;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHeader;
    // End of variables declaration//GEN-END:variables

    public class CurrentTime extends Thread {

        @Override
        public void run() {
            while (true) {
                try {
                    Calendar calendar = Calendar.getInstance();
                    int am_pm = calendar.get(Calendar.AM_PM);
                    String hour = calendar.get(Calendar.HOUR) + "";
                    String minute = calendar.get(Calendar.MINUTE) + "";
                    String second = calendar.get(Calendar.SECOND) + "";
                    String ampm;
                    if (am_pm == 0) {
                        ampm = "AM";
                    } else {
                        ampm = "PM";
                    }
                    if (second.length() == 1) {
                        second = "0" + second;
                    }
                    if (minute.length() == 1) {
                        minute = "0" + minute;
                    }
                    if (hour.length() == 1) {
                        hour = "0" + hour;
                    }
                    if (hour.equals("00")) {
                        hour = "12";
                    }

                    lblDateTime.setText(hour + ":" + minute + ":" + second + " " + ampm);
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }

            }
        }
    }

}
