/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controler.DBManager.userRole;
import static Controler.DBManager.userName;
import Controler.DBManager;
import Model.User;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gihan
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/Images/logo-icon.png"));
        Image image = imageIcon.getImage();
        this.setIconImage(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCompanyDetails = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblSlowgen = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSystemName = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        lblWebsiete = new javax.swing.JLabel();
        paneLoginDetails = new javax.swing.JPanel();
        bttnClose = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        bttnLogin = new javax.swing.JLabel();
        lblForgetPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Warehouse System");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCompanyDetails.setBackground(new java.awt.Color(153, 153, 153));
        panelCompanyDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo-icon.png"))); // NOI18N
        panelCompanyDetails.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 310, 100));

        lblSlowgen.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblSlowgen.setForeground(new java.awt.Color(255, 255, 255));
        lblSlowgen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSlowgen.setText("To keep connect with us.");
        panelCompanyDetails.add(lblSlowgen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 300, 40));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("info@smart-warehouse.com");
        panelCompanyDetails.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 300, 30));

        lblSystemName.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblSystemName.setForeground(new java.awt.Color(255, 255, 255));
        lblSystemName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSystemName.setText("Smart Warehouse System");
        panelCompanyDetails.add(lblSystemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 300, 40));

        lblCompany.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCompany.setForeground(new java.awt.Color(255, 255, 255));
        lblCompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompany.setText("Smart Warehouse (Pvt) Ltd.");
        panelCompanyDetails.add(lblCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 300, 30));

        lblWebsiete.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblWebsiete.setForeground(new java.awt.Color(255, 255, 255));
        lblWebsiete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWebsiete.setText("www.smart-warehouse.com");
        panelCompanyDetails.add(lblWebsiete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 300, 30));

        getContentPane().add(panelCompanyDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 460));

        paneLoginDetails.setBackground(new java.awt.Color(255, 255, 255));
        paneLoginDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close-butn.png"))); // NOI18N
        bttnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttnCloseMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bttnCloseMousePressed(evt);
            }
        });
        paneLoginDetails.add(bttnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, -2, -1, -1));

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(102, 102, 102));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("Login");
        paneLoginDetails.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 510, 90));

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPassword.setText("Password");
        paneLoginDetails.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        paneLoginDetails.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 390, 40));

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsername.setText("Username");
        paneLoginDetails.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneLoginDetails.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 390, 40));

        bttnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttnLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bttnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login-butn.png"))); // NOI18N
        bttnLogin.setText("Login");
        bttnLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bttnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bttnLoginMousePressed(evt);
            }
        });
        paneLoginDetails.add(bttnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 130, 40));

        lblForgetPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForgetPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/forget-butn.png"))); // NOI18N
        lblForgetPassword.setText("Forget");
        paneLoginDetails.add(lblForgetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 90, -1));

        getContentPane().add(paneLoginDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 510, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void bttnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnCloseMouseClicked

        this.dispose();
    }//GEN-LAST:event_bttnCloseMouseClicked

    private void bttnLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnLoginMousePressed

        String userName = txtUsername.getText();
        String pass = txtPassword.getText();

        User user = new User(userName, pass);

        DBManager dbManager = new DBManager();

        boolean flag = dbManager.checkUser(user);

        if (flag) {

            JOptionPane.showMessageDialog(null, userName+" ("+userRole+")"+"  Welcome to the System.", "Message", JOptionPane.INFORMATION_MESSAGE);

                Home homeFame = new Home(userRole);
                this.setAlwaysOnTop(false);
                this.setVisible(false);
                homeFame.setVisible(true);
            this.dispose();
        } else {

            JOptionPane.showMessageDialog(null, "Login Fail!!. Your username or password is incorrect.", "Error!!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_bttnLoginMousePressed

    private void bttnCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnCloseMousePressed

        this.dispose();
    }//GEN-LAST:event_bttnCloseMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bttnClose;
    private javax.swing.JLabel bttnLogin;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblForgetPassword;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSlowgen;
    private javax.swing.JLabel lblSystemName;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWebsiete;
    private javax.swing.JPanel paneLoginDetails;
    private javax.swing.JPanel panelCompanyDetails;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
