/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controler.DBManager.userName;
import static Controler.DBManager.userRole;
import Controler.DBManager;
import Model.Client;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gihan
 */
public class ManageClient extends javax.swing.JFrame {

    /**
     * Creates new form RegisterClient
     */
    SimpleDateFormat dateFormat;
    Date systemDate;

    public ManageClient() {
        initComponents();
        setName("Manage Clent");
        
        if (userRole.equals("Operator")) {
            lblRemoveButn.setVisible(false);
            lblRemove.setVisible(false);
        }

        systemDate = new Date();
        dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        getAllClientDetails();
    }

    ManageClient(String frame) {
        initComponents();
        setName("Manage Clent");

        if (frame.equals("View")) {
            lblRemoveButn.setVisible(false);
            lblRemove.setVisible(false);
            lblUpdateButn.setVisible(false);
            lblUpdate.setVisible(false);
        }
        systemDate = new Date();
        dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        getAllClientDetails();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblBackButtn = new javax.swing.JLabel();
        lblFrameName = new javax.swing.JLabel();
        lblHeadBanner = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblClientCode = new javax.swing.JLabel();
        txtClientCode = new javax.swing.JTextField();
        lblClientName = new javax.swing.JLabel();
        txtClientName = new javax.swing.JTextField();
        lblButnSearch = new javax.swing.JLabel();
        lblAddressNo = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        lblStreet = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblContactNo = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        lblFax = new javax.swing.JLabel();
        txtFaxNo = new javax.swing.JTextField();
        lblContactPerson = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblMobile = new javax.swing.JLabel();
        txtMobileNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClient = new javax.swing.JTable();
        lblUpdateButn = new javax.swing.JLabel();
        lblUpdate = new javax.swing.JLabel();
        lblCloseButtn1 = new javax.swing.JLabel();
        lblRemoveButn = new javax.swing.JLabel();
        lblRemove = new javax.swing.JLabel();
        lblHomeButn = new javax.swing.JLabel();
        lblRefreshButtn = new javax.swing.JLabel();
        lblRefresh = new javax.swing.JLabel();
        back_1 = new javax.swing.JLabel();
        back_2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBackButtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit-butn-small.png"))); // NOI18N
        lblBackButtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBackButtnMousePressed(evt);
            }
        });
        panelHeader.add(lblBackButtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 40, 40));

        jPanel1.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 40));

        lblFrameName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFrameName.setForeground(new java.awt.Color(255, 255, 255));
        lblFrameName.setText("Manage Client");
        jPanel1.add(lblFrameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 370, 40));

        lblHeadBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main-pic.jpg"))); // NOI18N
        jPanel1.add(lblHeadBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 40, 1360, 110));

        jSeparator1.setAlignmentX(5.0F);
        jSeparator1.setAlignmentY(5.0F);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 870, 20));

        lblClientCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblClientCode.setText("Client Code");
        jPanel1.add(lblClientCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 90, 30));

        txtClientCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtClientCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientCodeActionPerformed(evt);
            }
        });
        txtClientCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClientCodeKeyPressed(evt);
            }
        });
        jPanel1.add(txtClientCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 150, 30));

        lblClientName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblClientName.setText("Client Name");
        jPanel1.add(lblClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 90, 30));

        txtClientName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientNameActionPerformed(evt);
            }
        });
        txtClientName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClientNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClientNameKeyTyped(evt);
            }
        });
        jPanel1.add(txtClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 410, 30));

        lblButnSearch.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblButnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-butn.png"))); // NOI18N
        lblButnSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblButnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblButnSearchMousePressed(evt);
            }
        });
        jPanel1.add(lblButnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 170, -1, 40));

        lblAddressNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddressNo.setText("Address No.");
        jPanel1.add(lblAddressNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 110, 30));

        txtNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 260, 30));

        lblStreet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStreet.setText("Street");
        jPanel1.add(lblStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 110, 30));

        txtStreet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 410, 30));

        lblCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCity.setText("City");
        jPanel1.add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 110, 30));

        txtCity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 260, 30));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("Email ");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 110, 30));

        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 410, 30));

        lblContactNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblContactNo.setText("Contact No.");
        jPanel1.add(lblContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 100, 30));

        txtContactNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtContactNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContactNoFocusLost(evt);
            }
        });
        txtContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactNoKeyTyped(evt);
            }
        });
        jPanel1.add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 260, 30));

        lblFax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFax.setText("Fax");
        jPanel1.add(lblFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 100, 30));

        txtFaxNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtFaxNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 410, 30));

        lblContactPerson.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblContactPerson.setText("Contact Person");
        jPanel1.add(lblContactPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 130, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 130, 10));

        lblFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFirstName.setText("First Name");
        jPanel1.add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 110, 30));

        txtFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyTyped(evt);
            }
        });
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 260, 30));

        lblLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLastName.setText("Last Name");
        jPanel1.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 100, 30));

        txtLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastNameKeyTyped(evt);
            }
        });
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 410, 30));

        lblMobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMobile.setText("Mobile No");
        jPanel1.add(lblMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 110, 30));

        txtMobileNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobileNoKeyTyped(evt);
            }
        });
        jPanel1.add(txtMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 260, 30));

        tblClient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client Code", "Client Name", "Address", "Email", "Contact", "Contact Person", "Mobile No", "Enter Person"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClient.setGridColor(new java.awt.Color(255, 255, 255));
        tblClient.setRowHeight(20);
        tblClient.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tblClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClient);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 1120, 200));

        lblUpdateButn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update-butn-big.png"))); // NOI18N
        lblUpdateButn.setText("Delete");
        lblUpdateButn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUpdateButnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUpdateButnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblUpdateButnMousePressed(evt);
            }
        });
        jPanel1.add(lblUpdateButn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 820, 70, 70));

        lblUpdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdate.setText("Update");
        jPanel1.add(lblUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 890, 70, 30));

        lblCloseButtn1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCloseButtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseButtn1.setText("Home");
        jPanel1.add(lblCloseButtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 890, 70, 30));

        lblRemoveButn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove-butn-big.png"))); // NOI18N
        lblRemoveButn.setText("Update");
        lblRemoveButn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRemoveButnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRemoveButnMouseExited(evt);
            }
        });
        jPanel1.add(lblRemoveButn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 820, 70, 70));

        lblRemove.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRemove.setText("Remove");
        jPanel1.add(lblRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 890, 70, 30));

        lblHomeButn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-butn.png"))); // NOI18N
        lblHomeButn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeButnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeButnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHomeButnMousePressed(evt);
            }
        });
        jPanel1.add(lblHomeButn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 820, 70, 70));

        lblRefreshButtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRefreshButtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh-butn.png"))); // NOI18N
        lblRefreshButtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRefreshButtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRefreshButtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRefreshButtnMousePressed(evt);
            }
        });
        jPanel1.add(lblRefreshButtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 820, 70, 70));

        lblRefresh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRefresh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRefresh.setText("Refresh");
        jPanel1.add(lblRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 890, 70, 30));

        back_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wave-pack.png"))); // NOI18N
        jPanel1.add(back_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-380, 30, 1280, 520));

        back_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wave-back3.png"))); // NOI18N
        jPanel1.add(back_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 590, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 930));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackButtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackButtnMousePressed
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Warning", JOptionPane.YES_NO_OPTION) == 0) {
            this.setAlwaysOnTop(false);
            this.dispose();
        }
    }//GEN-LAST:event_lblBackButtnMousePressed

    private void tblClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientMouseClicked

        if (evt.getClickCount() == 2) {
            clearFields();
            searchClientByClientCode(tblClient.getValueAt(tblClient.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_tblClientMouseClicked

    private void lblRefreshButtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRefreshButtnMousePressed
        clearFields();
        getAllClientDetails();
    }//GEN-LAST:event_lblRefreshButtnMousePressed

    private void txtClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientNameActionPerformed

        searchClient(txtClientName.getText());
    }//GEN-LAST:event_txtClientNameActionPerformed

    private void txtClientCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientCodeActionPerformed

        searchClientByClientCode(txtClientCode.getText());
    }//GEN-LAST:event_txtClientCodeActionPerformed

    private void txtClientNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClientNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            new ClientSearch(this) {
                public boolean close() {
                    this.dispose();
                    return false;
                }
            }.setVisible(true);

        }
    }//GEN-LAST:event_txtClientNameKeyPressed

    private void txtClientCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClientCodeKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {

            txtClientName.setText("");
            txtNo.setText("");
            txtStreet.setText("");
            txtCity.setText("");
            txtEmail.setText("");
            txtContactNo.setText("");
            txtFaxNo.setText("");
            txtFirstName.setText("");
            txtLastName.setText("");
            txtMobileNo.setText("");
        }
    }//GEN-LAST:event_txtClientCodeKeyPressed

    private void lblHomeButnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeButnMousePressed

        this.setAlwaysOnTop(false);
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want go to home ?", "Message", JOptionPane.YES_NO_OPTION) == 0) {
            Home home = new Home(userRole);
            home.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lblHomeButnMousePressed

    private void txtClientNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClientNameKeyTyped


    }//GEN-LAST:event_txtClientNameKeyTyped

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost

        if (!txtEmail.getText().isEmpty()) {

            boolean flag = DBManager.textFieldEmailAddress(txtEmail.getText());
            if (flag) {
                txtContactNo.grabFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Email address is invalid.", "Invalid", 2);
                txtEmail.grabFocus();
            }
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void lblButnSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblButnSearchMousePressed

        if (!txtClientCode.getText().isEmpty() && !txtClientCode.getText().isEmpty()) {
            searchClientByClientCode(txtClientCode.getText());
        } else if (!txtClientCode.getText().isEmpty() && txtClientCode.getText().isEmpty()) {
            searchClientByClientCode(txtClientCode.getText());
        } else if (txtClientCode.getText().isEmpty() && !txtClientCode.getText().isEmpty()) {

        }
    }//GEN-LAST:event_lblButnSearchMousePressed

    private void txtFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyTyped
        DBManager.textFieldLettersOnly(evt);
    }//GEN-LAST:event_txtFirstNameKeyTyped

    private void txtLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyTyped
        DBManager.textFieldLettersOnly(evt);
    }//GEN-LAST:event_txtLastNameKeyTyped

    private void txtMobileNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileNoKeyTyped
        DBManager.textFieldNumberOnly(evt);
    }//GEN-LAST:event_txtMobileNoKeyTyped

    private void txtContactNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNoKeyTyped
        DBManager.textFieldNumberOnly(evt);
    }//GEN-LAST:event_txtContactNoKeyTyped

    private void txtContactNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContactNoFocusLost
        /*
        Check the mobile validation if the Contact number TextFiled is not empty
         */
        if (!txtContactNo.getText().isEmpty()) {

            boolean flag = DBManager.textFieldTelephoneNumber(txtContactNo.getText());
            if (flag) {
                txtFaxNo.grabFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Contact Number is invalid.", "Invalid", 2);
                txtContactNo.grabFocus();
            }
        }
    }//GEN-LAST:event_txtContactNoFocusLost

    private void lblUpdateButnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateButnMousePressed

        if (JOptionPane.showConfirmDialog(null, "Are you sure you want update client ?", "Message", JOptionPane.YES_NO_OPTION) == 0) {

            String clientCode = txtClientCode.getText();
            String clientName = txtClientName.getText();
            String addressNo = txtNo.getText();
            String street = txtStreet.getText();
            String city = txtCity.getText();
            String email = txtEmail.getText();
            String fax = txtFaxNo.getText();
            String contactNo = txtContactNo.getText();
            String firstName = txtFirstName.getText();
            String latName = txtLastName.getText();
            String mobileNo = txtMobileNo.getText();
            String updatePerson = userName;
            String updateDate = dateFormat.format(systemDate);

            if (clientName.equals("")) {
                JOptionPane.showMessageDialog(null, "Client name can't be empty.", "Empty Field Error", JOptionPane.INFORMATION_MESSAGE);
            } else if (contactNo.equals("")) {
                JOptionPane.showMessageDialog(null, "Client contact number can't be empty.", "Empty Field Error", JOptionPane.INFORMATION_MESSAGE);
            } else if ((firstName.isEmpty() || firstName.isEmpty()) && mobileNo.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Client Contact person information cant't be empty", "Invalid", JOptionPane.INFORMATION_MESSAGE);
            } else {

                Client client = new Client(clientCode, clientName, addressNo, street, city, email, fax, contactNo, firstName, latName, mobileNo, updatePerson, updateDate);
                boolean flag = DBManager.updateClient(client);

                if (flag) {
                    JOptionPane.showMessageDialog(null, "Client update successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    clearFields();
                    getAllClientDetails();
                } else {
                    JOptionPane.showMessageDialog(null, "Client update fail.", "Error!", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_lblUpdateButnMousePressed

    private void lblRemoveButnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveButnMouseEntered
         lblRemoveButn.setBounds(710, 835, 70, 70);
    }//GEN-LAST:event_lblRemoveButnMouseEntered

    private void lblRemoveButnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveButnMouseExited
         lblRemoveButn.setBounds(710, 830, 70, 70);
    }//GEN-LAST:event_lblRemoveButnMouseExited

    private void lblUpdateButnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateButnMouseEntered
       lblUpdateButn.setBounds(830, 825, 70, 70);
    }//GEN-LAST:event_lblUpdateButnMouseEntered

    private void lblUpdateButnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateButnMouseExited
         lblUpdateButn.setBounds(830, 820, 70, 70);
    }//GEN-LAST:event_lblUpdateButnMouseExited

    private void lblRefreshButtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRefreshButtnMouseEntered
         lblRefreshButtn.setBounds(950, 825, 70, 70);
    }//GEN-LAST:event_lblRefreshButtnMouseEntered

    private void lblRefreshButtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRefreshButtnMouseExited
          lblRefreshButtn.setBounds(950, 820, 70, 70);
    }//GEN-LAST:event_lblRefreshButtnMouseExited

    private void lblHomeButnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeButnMouseEntered
        lblHomeButn.setBounds(1070, 825, 70, 70);
    }//GEN-LAST:event_lblHomeButnMouseEntered

    private void lblHomeButnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeButnMouseExited
       lblHomeButn.setBounds(1070, 820, 70, 70);
    }//GEN-LAST:event_lblHomeButnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ManageClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_1;
    private javax.swing.JLabel back_2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAddressNo;
    private javax.swing.JLabel lblBackButtn;
    private javax.swing.JLabel lblButnSearch;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblClientCode;
    private javax.swing.JLabel lblClientName;
    private javax.swing.JLabel lblCloseButtn1;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblContactPerson;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFrameName;
    private javax.swing.JLabel lblHeadBanner;
    private javax.swing.JLabel lblHomeButn;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblRefresh;
    private javax.swing.JLabel lblRefreshButtn;
    private javax.swing.JLabel lblRemove;
    private javax.swing.JLabel lblRemoveButn;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JLabel lblUpdateButn;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTable tblClient;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtClientCode;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNo;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtStreet;
    // End of variables declaration//GEN-END:variables

    private void getAllClientDetails() {

        DBManager dbManager = new DBManager();
        ArrayList<Client> clientArray = dbManager.getAllClientDetails();
        DefaultTableModel tblModel = (DefaultTableModel) tblClient.getModel();

        for (Client client : clientArray) {
            System.out.println("client_code= " + client.getClientCode());
            Object columns[] = new Object[8];

            columns[0] = client.getClientCode();
            columns[1] = client.getClientName();
            columns[2] = client.getNo() + " " + client.getStreet() + " " + client.getCity();
            columns[3] = client.getEmail();
            columns[4] = client.getContactNo();
            columns[5] = client.getFirstName() + " " + client.getLastName();
            columns[6] = client.getMobileNo();
            columns[7] = client.getRegisterPerson();
            tblModel.addRow(columns);
        }

    }

    private void clearFields() {
        txtClientCode.setText("");
        txtClientName.setText("");
        txtNo.setText("");
        txtStreet.setText("");
        txtCity.setText("");
        txtEmail.setText("");
        txtContactNo.setText("");
        txtFaxNo.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtMobileNo.setText("");
    }

    void searchClient(String clientName) {
        Client client = new Client(clientName);
        DBManager dbManager = new DBManager();
        client = dbManager.searchClientByClientName(client);

        if (client == null) {

            JOptionPane.showMessageDialog(null, "No client record found.", "No Record", JOptionPane.WARNING_MESSAGE);
        } else {

            txtClientCode.setText(client.getClientCode());
            txtClientName.setText(client.getClientName());
            txtNo.setText(client.getNo());
            txtStreet.setText(client.getStreet());
            txtCity.setText(client.getCity());
            txtEmail.setText(client.getEmail());
            txtContactNo.setText(client.getContactNo());
            txtFaxNo.setText(client.getFax());
            txtFirstName.setText(client.getFirstName());
            txtLastName.setText(client.getLastName());
            txtMobileNo.setText(client.getMobileNo());
        }
    }

    private void searchClientByClientCode(String clientCode) {

        Client client = new Client();
        client.setClientCode(clientCode);

        DBManager dbManager = new DBManager();
        client = dbManager.searchClientByClientCode(client);

        if (client == null) {

            JOptionPane.showMessageDialog(null, "Invalid Client Code.", "Invalid", JOptionPane.WARNING_MESSAGE);
        } else {

            txtClientCode.setText(client.getClientCode());
            txtClientName.setText(client.getClientName());
            txtNo.setText(client.getNo());
            txtStreet.setText(client.getStreet());
            txtCity.setText(client.getCity());
            txtEmail.setText(client.getEmail());
            txtContactNo.setText(client.getContactNo());
            txtFaxNo.setText(client.getFax());
            txtFirstName.setText(client.getFirstName());
            txtLastName.setText(client.getLastName());
            txtMobileNo.setText(client.getMobileNo());
        }
    }
}
