/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controler.DBManager.userRole;
import Controler.DBManager;
import Model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Gihan
 */
public class ManageUser extends javax.swing.JFrame {

    /**
     * Creates new form CreateUser
     */
    public ManageUser() {
        initComponents();

        AllMarkUnvisible();
    }

    ManageUser(String frame) {
        initComponents();

        AllMarkUnvisible();

        if (frame.equals("View")) {
            butnUpdate.setVisible(false);
            lblUpdate.setVisible(false);
            butnRemove.setVisible(false);
            lblRemove.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBack = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblBackButtn = new javax.swing.JLabel();
        lblFrameName = new javax.swing.JLabel();
        lblHeadBanner = new javax.swing.JLabel();
        lblEmpNo = new javax.swing.JLabel();
        txtEmpNo = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblMobileNo = new javax.swing.JLabel();
        txtMobileNo = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblUserRole = new javax.swing.JLabel();
        comUserRole = new javax.swing.JComboBox<>();
        lblConfirm = new javax.swing.JLabel();
        txtConfirm = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        butnHome = new javax.swing.JLabel();
        butnRemove = new javax.swing.JLabel();
        lblHom = new javax.swing.JLabel();
        butnRefresh = new javax.swing.JLabel();
        lblRemove = new javax.swing.JLabel();
        lblRefresh = new javax.swing.JLabel();
        butnUpdate = new javax.swing.JLabel();
        lblUpdate = new javax.swing.JLabel();
        butnSearch = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblCrossMark = new javax.swing.JLabel();
        lblCrossMark1 = new javax.swing.JLabel();
        lblCheckMark = new javax.swing.JLabel();
        lblCheckMark1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBack.setBackground(new java.awt.Color(255, 255, 255));
        panelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBackButtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit-butn-small.png"))); // NOI18N
        lblBackButtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBackButtnMousePressed(evt);
            }
        });
        panelHeader.add(lblBackButtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 40, 40));

        panelBack.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 40));

        lblFrameName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFrameName.setForeground(new java.awt.Color(255, 255, 255));
        lblFrameName.setText("Manage User");
        panelBack.add(lblFrameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 370, 40));

        lblHeadBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main-pic.jpg"))); // NOI18N
        panelBack.add(lblHeadBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 40, 1370, 110));

        lblEmpNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmpNo.setText("Employee No.");
        panelBack.add(lblEmpNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, 30));

        txtEmpNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmpNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpNoActionPerformed(evt);
            }
        });
        panelBack.add(txtEmpNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 140, 30));

        lblFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFirstName.setText("First Name");
        panelBack.add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 90, 30));

        txtFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyTyped(evt);
            }
        });
        panelBack.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 250, 30));

        lblLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLastName.setText("Last Name");
        panelBack.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 90, 30));

        txtLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastNameKeyTyped(evt);
            }
        });
        panelBack.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 250, 30));

        lblMobileNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMobileNo.setText("Mobile Number");
        panelBack.add(lblMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 90, 30));

        txtMobileNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMobileNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMobileNoFocusLost(evt);
            }
        });
        txtMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobileNoKeyTyped(evt);
            }
        });
        panelBack.add(txtMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 250, 30));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("Email");
        panelBack.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 90, 30));

        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        panelBack.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 250, 30));

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUserName.setText("User Name");
        panelBack.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 90, 30));

        txtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBack.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 250, 30));

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPassword.setText("Password");
        panelBack.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 70, 30));

        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBack.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 250, 30));

        lblUserRole.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUserRole.setText("User Role");
        panelBack.add(lblUserRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 90, 30));

        comUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "******* User Role *******", "Manager", "Operator", " " }));
        panelBack.add(comUserRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 250, 30));

        lblConfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConfirm.setText("Confirm");
        panelBack.add(lblConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 70, 30));

        txtConfirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBack.add(txtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 250, 30));
        panelBack.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 350, 20));

        butnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        butnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-butn.png"))); // NOI18N
        butnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butnHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butnHomeMousePressed(evt);
            }
        });
        panelBack.add(butnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 70, 70));

        butnRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        butnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove-butn-big.png"))); // NOI18N
        butnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butnRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butnRemoveMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butnRemoveMousePressed(evt);
            }
        });
        panelBack.add(butnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 70, 70));

        lblHom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblHom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHom.setText("Home");
        panelBack.add(lblHom, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 600, 70, -1));

        butnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh-butn.png"))); // NOI18N
        butnRefresh.setText("Refresh");
        butnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butnRefreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butnRefreshMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butnRefreshMousePressed(evt);
            }
        });
        panelBack.add(butnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, 70, 70));

        lblRemove.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRemove.setText("Romove");
        panelBack.add(lblRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 600, 70, -1));

        lblRefresh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRefresh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRefresh.setText("Refresh");
        panelBack.add(lblRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 600, 70, -1));

        butnUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        butnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update-butn-big.png"))); // NOI18N
        butnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butnUpdateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butnUpdateMousePressed(evt);
            }
        });
        panelBack.add(butnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 70, 70));

        lblUpdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdate.setText("Update");
        panelBack.add(lblUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 600, 70, -1));

        butnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-butn.png"))); // NOI18N
        butnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butnSearchMousePressed(evt);
            }
        });
        panelBack.add(butnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back-pic1.png"))); // NOI18N
        panelBack.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 500, 500));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wave-pack.png"))); // NOI18N
        panelBack.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-420, 30, 1380, 640));

        lblCrossMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross-mark.png"))); // NOI18N
        panelBack.add(lblCrossMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 40, 30));

        lblCrossMark1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross-mark.png"))); // NOI18N
        panelBack.add(lblCrossMark1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 40, 30));

        lblCheckMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check-mark.png"))); // NOI18N
        panelBack.add(lblCheckMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 40, 30));

        lblCheckMark1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check-mark.png"))); // NOI18N
        panelBack.add(lblCheckMark1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 40, 30));

        getContentPane().add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackButtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackButtnMousePressed
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Warning", JOptionPane.YES_NO_OPTION) == 0) {
            this.setAlwaysOnTop(false);
            this.dispose();
        }
    }//GEN-LAST:event_lblBackButtnMousePressed

    private void txtEmpNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpNoActionPerformed

        employeeSearch(txtEmpNo.getText());

    }//GEN-LAST:event_txtEmpNoActionPerformed

    private void butnUpdateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnUpdateMousePressed

        if (JOptionPane.showConfirmDialog(null, "Are you sure you want update user ?", "Message", JOptionPane.YES_NO_OPTION) == 0) {

            String empNo = txtEmpNo.getText();
            String fName = txtFirstName.getText();
            String lName = txtLastName.getText();
            String mobile = txtMobileNo.getText();
            String email = txtEmail.getText();
            String username = txtUserName.getText();
            String pass = txtPassword.getText();
            String userRole = (String) comUserRole.getSelectedItem();
            int status = 1;

            if (empNo.equals("")) {
                JOptionPane.showMessageDialog(null, "Employee ID can't be empty.", "Empty Field Error!", JOptionPane.INFORMATION_MESSAGE);
            } else if (username.equals("") && pass.equals("")) {
                JOptionPane.showMessageDialog(null, "Username & password can't be empty.", "Empty Field Error!", JOptionPane.INFORMATION_MESSAGE);
            } else if (userRole.equals("******* User Role *******")) {
                JOptionPane.showMessageDialog(null, "User role is invalid.", "Invalid!", JOptionPane.INFORMATION_MESSAGE);
            } else if (!pass.equals(txtConfirm.getText())) {
                AllMarkUnvisible();
                CrossMarkVisible();
                JOptionPane.showMessageDialog(null, "Those passwords didn’t match. Try again.", "Mismatch Error", JOptionPane.WARNING_MESSAGE);
            } else {

                AllMarkUnvisible();
                CheckMarkVisible();

                User user = new User(empNo, fName, lName, mobile, email, username, pass, userRole, status);
                DBManager dBManager = new DBManager();

                boolean flag = dBManager.updateUser(user);

                if (flag) {

                    JOptionPane.showMessageDialog(null, "User update successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(null, "User update fail.", "Error!", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_butnUpdateMousePressed

    private void butnRefreshMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnRefreshMousePressed

        if (JOptionPane.showConfirmDialog(null, "Are you sure to clear the fields ?", "Message", JOptionPane.YES_NO_OPTION) == 0) {
            clearFields();
        }


    }//GEN-LAST:event_butnRefreshMousePressed

    private void butnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnHomeMousePressed

        if (JOptionPane.showConfirmDialog(null, "Are you sure you want go to home ?", "Message", JOptionPane.YES_NO_OPTION) == 0) {
            this.setAlwaysOnTop(false);

            Home home = new Home(userRole);
            home.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_butnHomeMousePressed

    private void butnRemoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnRemoveMousePressed

        if (JOptionPane.showConfirmDialog(null, "Are you sure you want remove user ?", "Message", JOptionPane.YES_NO_OPTION) == 0) {

            String empNo = txtEmpNo.getText();
            User user = new User(empNo);
            DBManager dbManager = new DBManager();
            boolean flag = dbManager.removeUser(user);

            if (flag) {

                JOptionPane.showMessageDialog(null, "User removed successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                txtEmpNo.setText("");
                txtFirstName.setText("");
                txtLastName.setText("");
                txtMobileNo.setText("");
                txtEmail.setText("");
                txtUserName.setText("");
                txtPassword.setText("");
                comUserRole.setSelectedItem("******* User Role *******");
                txtConfirm.setText("");

            } else {
                JOptionPane.showMessageDialog(null, "User removing fail.", "Error!", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_butnRemoveMousePressed

    private void butnSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnSearchMousePressed

        employeeSearch(txtEmpNo.getText());
    }//GEN-LAST:event_butnSearchMousePressed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost

        if (!txtEmail.getText().isEmpty()) {

            boolean flag = DBManager.textFieldEmailAddress(txtEmail.getText());
            if (flag) {
                txtPassword.grabFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Email address is invalid.", "Invalid", 2);
                txtEmail.grabFocus();
            }
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void butnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnUpdateMouseEntered
        butnUpdate.setBounds(490, 525, 70, 70);
    }//GEN-LAST:event_butnUpdateMouseEntered

    private void butnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnUpdateMouseExited
        butnUpdate.setBounds(490, 520, 70, 70);
    }//GEN-LAST:event_butnUpdateMouseExited

    private void butnRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnRemoveMouseEntered
        butnRemove.setBounds(610, 525, 70, 70);
    }//GEN-LAST:event_butnRemoveMouseEntered

    private void butnRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnRemoveMouseExited
        butnRemove.setBounds(610, 520, 70, 70);
    }//GEN-LAST:event_butnRemoveMouseExited

    private void butnRefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnRefreshMouseEntered
        butnRefresh.setBounds(730, 525, 70, 70);
    }//GEN-LAST:event_butnRefreshMouseEntered

    private void butnRefreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnRefreshMouseExited
        butnRefresh.setBounds(730, 520, 70, 70);
    }//GEN-LAST:event_butnRefreshMouseExited

    private void butnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnHomeMouseEntered
        butnHome.setBounds(850, 525, 70, 70);
    }//GEN-LAST:event_butnHomeMouseEntered

    private void butnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnHomeMouseExited
        butnHome.setBounds(850, 520, 70, 70);
    }//GEN-LAST:event_butnHomeMouseExited

    private void txtMobileNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMobileNoFocusLost
        if (!txtMobileNo.getText().isEmpty()) {

            boolean flag = DBManager.textFieldTelephoneNumber(txtMobileNo.getText());
            if (flag) {
                txtUserName.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Mobile Number is invalid.", "Invalid", 2);
                txtMobileNo.grabFocus();
            }
        }
    }//GEN-LAST:event_txtMobileNoFocusLost

    private void txtFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyTyped
       DBManager.textFieldLettersOnly(evt);
    }//GEN-LAST:event_txtFirstNameKeyTyped

    private void txtLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyTyped
       DBManager.textFieldLettersOnly(evt);
    }//GEN-LAST:event_txtLastNameKeyTyped

    private void txtMobileNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileNoKeyTyped
       DBManager.textFieldNumberOnly(evt);
    }//GEN-LAST:event_txtMobileNoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ManageUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel butnHome;
    private javax.swing.JLabel butnRefresh;
    private javax.swing.JLabel butnRemove;
    private javax.swing.JLabel butnSearch;
    private javax.swing.JLabel butnUpdate;
    private javax.swing.JComboBox<String> comUserRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBackButtn;
    private javax.swing.JLabel lblCheckMark;
    private javax.swing.JLabel lblCheckMark1;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblCrossMark;
    private javax.swing.JLabel lblCrossMark1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpNo;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFrameName;
    private javax.swing.JLabel lblHeadBanner;
    private javax.swing.JLabel lblHom;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMobileNo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRefresh;
    private javax.swing.JLabel lblRemove;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserRole;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField txtConfirm;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpNo;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        txtEmpNo.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtMobileNo.setText("");
        txtEmail.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
        comUserRole.setSelectedItem("******* User Role *******");
        txtConfirm.setText("");

        AllMarkUnvisible();
    }

    private void clearFieldsWithoutEmployeeID() {
        txtFirstName.setText("");
        txtLastName.setText("");
        txtMobileNo.setText("");
        txtEmail.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
        comUserRole.setSelectedItem("******* User Role *******");
        txtConfirm.setText("");

        AllMarkUnvisible();
    }

    private void CheckMarkVisible() {
        this.lblCheckMark.setVisible(true);
        this.lblCheckMark1.setVisible(true);
    }

    private void CrossMarkVisible() {
        this.lblCrossMark.setVisible(true);
        this.lblCrossMark1.setVisible(true);
    }

    private void AllMarkUnvisible() {
        this.lblCheckMark.setVisible(false);
        this.lblCrossMark.setVisible(false);
        this.lblCheckMark1.setVisible(false);
        this.lblCrossMark1.setVisible(false);
    }

    private void employeeSearch(String empNo) {
        User user = new User(empNo);
        DBManager dbManager = new DBManager();
        User searchUser = dbManager.searchUser(user);

        clearFieldsWithoutEmployeeID();

        if (empNo.equals("")) {
            JOptionPane.showMessageDialog(null, "Can't be search. Employee Number is empty.", "Empty Field", JOptionPane.INFORMATION_MESSAGE);
        } else if (searchUser == null) {

            JOptionPane.showMessageDialog(null, "Invalid Employee Number", "Invalid", JOptionPane.WARNING_MESSAGE);
        } else {

            txtEmpNo.setText(searchUser.getEmpId());
            txtFirstName.setText(searchUser.getfName());
            txtLastName.setText(searchUser.getlName());
            txtMobileNo.setText(searchUser.getMobileNo());
            txtEmail.setText(searchUser.getEmail());
            txtUserName.setText(searchUser.getUsername());
            txtPassword.setText(searchUser.getPassword());
            comUserRole.setSelectedItem(searchUser.getUserRole());
            txtConfirm.setText(searchUser.getPassword());
        }
    }
}
