/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controler.DBManager.userName;
import static Controler.DBManager.userRole;
import javax.swing.JOptionPane;

/**
 *
 * @author Gihan
 */
public class MenuUser extends javax.swing.JFrame {

    /**
     * Creates new form MenuStore
     */
    public MenuUser() {
        initComponents();
        
        lblUserName.setText(userName);
        lblUserType.setText(userRole);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNewUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblViewUser = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblEditUser = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserType = new javax.swing.JLabel();
        lblFrameName = new javax.swing.JLabel();
        lblHeadBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNewUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-user-icon.png"))); // NOI18N
        lblNewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNewUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNewUserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNewUserMousePressed(evt);
            }
        });
        jPanel1.add(lblNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 110, 130));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add New User");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 110, -1));

        lblViewUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/serch-user-icon.png"))); // NOI18N
        lblViewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewUserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblViewUserMousePressed(evt);
            }
        });
        jPanel1.add(lblViewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 110, 130));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("View User");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Update User");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 110, -1));

        lblEditUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit-user-icon.png"))); // NOI18N
        lblEditUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEditUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEditUserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEditUserMousePressed(evt);
            }
        });
        jPanel1.add(lblEditUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 110, 130));

        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-icon.png"))); // NOI18N
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHomeMousePressed(evt);
            }
        });
        jPanel1.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 110, 130));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Edit User");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back-pic4.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1030, 250));

        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("User Name");
        jPanel1.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 30));

        lblUserType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserType.setForeground(new java.awt.Color(255, 255, 255));
        lblUserType.setText("User Type");
        jPanel1.add(lblUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, 20));

        lblFrameName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFrameName.setForeground(new java.awt.Color(255, 255, 255));
        lblFrameName.setText("User Menu");
        jPanel1.add(lblFrameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 370, 40));

        lblHeadBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main-pic.jpg"))); // NOI18N
        jPanel1.add(lblHeadBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, 1080, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMousePressed

        this.setAlwaysOnTop(false);
        if (JOptionPane.showConfirmDialog(null, "Are you sure back to home?", "Warning", JOptionPane.YES_NO_OPTION) == 0) {
            Home home = new Home(userRole);
            home.setVisible(true);
            this.dispose();
            
        }

    }//GEN-LAST:event_lblHomeMousePressed

    private void lblNewUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewUserMouseEntered
        lblNewUser.setBounds(70, 170, 110, 130);
    }//GEN-LAST:event_lblNewUserMouseEntered

    private void lblNewUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewUserMouseExited
        lblNewUser.setBounds(70, 175, 110, 130);
    }//GEN-LAST:event_lblNewUserMouseExited

    private void lblViewUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewUserMouseEntered
        lblViewUser.setBounds(330, 170, 110, 130);
    }//GEN-LAST:event_lblViewUserMouseEntered

    private void lblViewUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewUserMouseExited
        lblViewUser.setBounds(330, 175, 110, 130);
    }//GEN-LAST:event_lblViewUserMouseExited

    private void lblEditUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditUserMouseEntered
        lblEditUser.setBounds(610, 170, 110, 130);
    }//GEN-LAST:event_lblEditUserMouseEntered

    private void lblEditUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditUserMouseExited
        lblEditUser.setBounds(610, 175, 110, 130);
    }//GEN-LAST:event_lblEditUserMouseExited

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        lblHome.setBounds(850, 170, 110, 130);
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        lblHome.setBounds(850, 175, 110, 130);
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblNewUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewUserMousePressed

        RegisterUser createUser = new RegisterUser();
        createUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblNewUserMousePressed

    private void lblViewUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewUserMousePressed

        ManageUser viewUser = new ManageUser("View");
        viewUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblViewUserMousePressed

    private void lblEditUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditUserMousePressed

        ManageUser editUser = new ManageUser();
        editUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblEditUserMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEditUser;
    private javax.swing.JLabel lblFrameName;
    private javax.swing.JLabel lblHeadBanner;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblNewUser;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JLabel lblViewUser;
    // End of variables declaration//GEN-END:variables
}
