/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controler.DBManager.userRole;
import javax.swing.JOptionPane;

/**
 *
 * @author Gihan
 */
public class MenuStore extends javax.swing.JFrame {

    /**
     * Creates new form MenuStore
     */
    public MenuStore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNewJob = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblViewJob = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCloseJob = new javax.swing.JLabel();
        lblEditJOb = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserType = new javax.swing.JLabel();
        lblFrameName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNewJob1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblViewJob1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCloseJob1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUserName1 = new javax.swing.JLabel();
        lblUserType1 = new javax.swing.JLabel();
        lblFrameName1 = new javax.swing.JLabel();
        lblHeadBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-icon-unfil.png"))); // NOI18N
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHomeMousePressed(evt);
            }
        });
        jPanel1.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 170, 110, 130));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Home");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 310, 110, -1));

        lblNewJob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewJob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/job-new.png"))); // NOI18N
        lblNewJob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNewJobMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNewJobMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNewJobMousePressed(evt);
            }
        });
        jPanel1.add(lblNewJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 110, 130));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("New JOb");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 110, -1));

        lblViewJob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewJob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/job-view.png"))); // NOI18N
        lblViewJob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewJobMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewJobMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblViewJobMousePressed(evt);
            }
        });
        jPanel1.add(lblViewJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 110, 130));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("View Job");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Close Job");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, 110, -1));

        lblCloseJob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseJob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/job-close.png"))); // NOI18N
        lblCloseJob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseJobMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseJobMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseJobMousePressed(evt);
            }
        });
        jPanel1.add(lblCloseJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 110, 130));

        lblEditJOb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditJOb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/job-edit.png"))); // NOI18N
        lblEditJOb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEditJObMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEditJObMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEditJObMousePressed(evt);
            }
        });
        jPanel1.add(lblEditJOb, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 110, 130));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Edit Job");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back-pic4.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1240, 250));

        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("User Name");
        jPanel1.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 30));

        lblUserType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserType.setForeground(new java.awt.Color(255, 255, 255));
        lblUserType.setText("User Type");
        jPanel1.add(lblUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, 20));

        lblFrameName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFrameName.setForeground(new java.awt.Color(255, 255, 255));
        lblFrameName.setText("Job Menu");
        jPanel1.add(lblFrameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 370, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNewJob1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewJob1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/job-new.png"))); // NOI18N
        lblNewJob1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNewJob1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNewJob1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNewJob1MousePressed(evt);
            }
        });
        jPanel2.add(lblNewJob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 110, 130));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("New JOb");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 110, -1));

        lblViewJob1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewJob1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/job-view.png"))); // NOI18N
        lblViewJob1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewJob1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewJob1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblViewJob1MousePressed(evt);
            }
        });
        jPanel2.add(lblViewJob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 110, 130));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("View Job");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 110, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Close Job");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 110, -1));

        lblCloseJob1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseJob1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/job-close.png"))); // NOI18N
        lblCloseJob1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseJob1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseJob1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseJob1MousePressed(evt);
            }
        });
        jPanel2.add(lblCloseJob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 110, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back-pic4.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1240, 250));

        lblUserName1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUserName1.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName1.setText("User Name");
        jPanel2.add(lblUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 30));

        lblUserType1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserType1.setForeground(new java.awt.Color(255, 255, 255));
        lblUserType1.setText("User Type");
        jPanel2.add(lblUserType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, 20));

        lblFrameName1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFrameName1.setForeground(new java.awt.Color(255, 255, 255));
        lblFrameName1.setText("Job Menu");
        jPanel2.add(lblFrameName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 370, 40));

        lblHeadBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main-pic.jpg"))); // NOI18N
        jPanel2.add(lblHeadBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -10, 1340, 150));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        lblHome.setBounds(1070, 175, 110, 130);
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        lblHome.setBounds(1070, 170, 110, 130);
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMousePressed

        if (JOptionPane.showConfirmDialog(null, "Are you sure back to home?", "Warning", JOptionPane.YES_NO_OPTION) == 0) {
            Home home = new Home(userRole);
            home.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_lblHomeMousePressed

    private void lblNewJobMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewJobMouseEntered
        lblNewJob.setBounds(70, 175, 110, 130);
    }//GEN-LAST:event_lblNewJobMouseEntered

    private void lblNewJobMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewJobMouseExited
        lblNewJob.setBounds(70, 170, 110, 130);
    }//GEN-LAST:event_lblNewJobMouseExited

    private void lblNewJobMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewJobMousePressed

        NewJob newJob = new NewJob();
        newJob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblNewJobMousePressed

    private void lblViewJobMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewJobMouseEntered
        lblViewJob.setBounds(330, 175, 110, 130);
    }//GEN-LAST:event_lblViewJobMouseEntered

    private void lblViewJobMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewJobMouseExited
        lblViewJob.setBounds(330, 170, 110, 130);
    }//GEN-LAST:event_lblViewJobMouseExited

    private void lblViewJobMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewJobMousePressed

        ViewAllJobs viewJobs = new ViewAllJobs();
        viewJobs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblViewJobMousePressed

    private void lblCloseJobMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseJobMouseEntered
        lblCloseJob.setBounds(840, 175, 110, 130);
    }//GEN-LAST:event_lblCloseJobMouseEntered

    private void lblCloseJobMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseJobMouseExited
        lblCloseJob.setBounds(840, 170, 110, 130);
    }//GEN-LAST:event_lblCloseJobMouseExited

    private void lblCloseJobMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseJobMousePressed

        CloseJob closeJob = new CloseJob();
        closeJob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCloseJobMousePressed

    private void lblEditJObMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditJObMouseEntered
        lblEditJOb.setBounds(600, 175, 110, 130);
    }//GEN-LAST:event_lblEditJObMouseEntered

    private void lblEditJObMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditJObMouseExited
        lblEditJOb.setBounds(600, 170, 110, 130);
    }//GEN-LAST:event_lblEditJObMouseExited

    private void lblEditJObMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditJObMousePressed
        EditJob editJob = new EditJob();
        editJob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblEditJObMousePressed

    private void lblNewJob1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewJob1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNewJob1MouseEntered

    private void lblNewJob1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewJob1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNewJob1MouseExited

    private void lblNewJob1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewJob1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNewJob1MousePressed

    private void lblViewJob1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewJob1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblViewJob1MouseEntered

    private void lblViewJob1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewJob1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblViewJob1MouseExited

    private void lblViewJob1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewJob1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblViewJob1MousePressed

    private void lblCloseJob1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseJob1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseJob1MouseEntered

    private void lblCloseJob1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseJob1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseJob1MouseExited

    private void lblCloseJob1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseJob1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseJob1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuStore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCloseJob;
    private javax.swing.JLabel lblCloseJob1;
    private javax.swing.JLabel lblEditJOb;
    private javax.swing.JLabel lblFrameName;
    private javax.swing.JLabel lblFrameName1;
    private javax.swing.JLabel lblHeadBanner;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblNewJob;
    private javax.swing.JLabel lblNewJob1;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserName1;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JLabel lblUserType1;
    private javax.swing.JLabel lblViewJob;
    private javax.swing.JLabel lblViewJob1;
    // End of variables declaration//GEN-END:variables
}
