/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controler.DBManager.userRole;
import javax.swing.JOptionPane;

/**
 *
 * @author Gihan
 */
public class MenuRepots extends javax.swing.JFrame {

    /**
     * Creates new form MenuStore
     */
    public MenuRepots() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblViewAllClient = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblViewAllJobs = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblViewAllItems = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserType = new javax.swing.JLabel();
        lblFrameName = new javax.swing.JLabel();
        lblHeadBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-icon.png"))); // NOI18N
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHomeMousePressed(evt);
            }
        });
        jPanel1.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 110, 130));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Home");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 110, -1));

        lblViewAllClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewAllClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/view-client.png"))); // NOI18N
        lblViewAllClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewAllClientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewAllClientMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblViewAllClientMousePressed(evt);
            }
        });
        jPanel1.add(lblViewAllClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 110, 130));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("View All Client");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 110, -1));

        lblViewAllJobs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewAllJobs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/invoice_icon.png"))); // NOI18N
        lblViewAllJobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewAllJobsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewAllJobsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblViewAllJobsMousePressed(evt);
            }
        });
        jPanel1.add(lblViewAllJobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 110, 130));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("View All Jobs");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("View All Items");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 110, -1));

        lblViewAllItems.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewAllItems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/item-icon.png"))); // NOI18N
        lblViewAllItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewAllItemsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewAllItemsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblViewAllItemsMousePressed(evt);
            }
        });
        jPanel1.add(lblViewAllItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 110, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back-pic4.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1030, 250));

        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("User Name");
        jPanel1.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 30));

        lblUserType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserType.setForeground(new java.awt.Color(255, 255, 255));
        lblUserType.setText("User Type");
        jPanel1.add(lblUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, 20));

        lblFrameName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFrameName.setForeground(new java.awt.Color(255, 255, 255));
        lblFrameName.setText("Report Menu");
        jPanel1.add(lblFrameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 370, 40));

        lblHeadBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main-pic.jpg"))); // NOI18N
        jPanel1.add(lblHeadBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, 1080, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        lblHome.setBounds(850, 175, 110, 130);
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        lblHome.setBounds(850, 170, 110, 130);
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMousePressed

        if (JOptionPane.showConfirmDialog(null, "Are you sure back to home?", "Warning", JOptionPane.YES_NO_OPTION) == 0) {
            Home home = new Home(userRole);
            home.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_lblHomeMousePressed

    private void lblViewAllClientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewAllClientMouseEntered
        lblViewAllClient.setBounds(70, 175, 110, 130);
    }//GEN-LAST:event_lblViewAllClientMouseEntered

    private void lblViewAllClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewAllClientMouseExited
        lblViewAllClient.setBounds(70, 170, 110, 130);
    }//GEN-LAST:event_lblViewAllClientMouseExited

    private void lblViewAllClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewAllClientMousePressed

        ViewAllClients viewClient = new ViewAllClients();
        viewClient.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblViewAllClientMousePressed

    private void lblViewAllJobsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewAllJobsMouseEntered
        lblViewAllJobs.setBounds(330, 175, 110, 130);
    }//GEN-LAST:event_lblViewAllJobsMouseEntered

    private void lblViewAllJobsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewAllJobsMouseExited
        lblViewAllJobs.setBounds(330, 170, 110, 130);
    }//GEN-LAST:event_lblViewAllJobsMouseExited

    private void lblViewAllJobsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewAllJobsMousePressed

        ViewAllJobs viewJobs = new ViewAllJobs();
        viewJobs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblViewAllJobsMousePressed

    private void lblViewAllItemsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewAllItemsMouseEntered
        lblViewAllItems.setBounds(610, 175, 110, 130);
    }//GEN-LAST:event_lblViewAllItemsMouseEntered

    private void lblViewAllItemsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewAllItemsMouseExited
        lblViewAllItems.setBounds(610, 170, 110, 130);
    }//GEN-LAST:event_lblViewAllItemsMouseExited

    private void lblViewAllItemsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewAllItemsMousePressed

        ViewAllItems viewAllItems = new ViewAllItems();
        viewAllItems.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblViewAllItemsMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRepots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuRepots().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFrameName;
    private javax.swing.JLabel lblHeadBanner;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JLabel lblViewAllClient;
    private javax.swing.JLabel lblViewAllItems;
    private javax.swing.JLabel lblViewAllJobs;
    // End of variables declaration//GEN-END:variables
}
