/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controler.DBManager.userRole;
import Controler.DBManager;
import Model.Client;
import Model.Invoice;
import Model.Job;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gihan
 */
public class NewJob extends javax.swing.JFrame {

    /**
     * Creates new form NewStorage
     */
    Date date;
    SimpleDateFormat dateFormat;
    double subTotal = 0.0;
    DefaultTableModel model;

    public NewJob() {
        initComponents();

        setName("New Job");

        date = new Date();
        dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        dcJobDate.setDateFormatString(dateFormat.toLocalizedPattern());
        dcJobDate.setDate(date);

        dcFromtDate.setDateFormatString(dateFormat.toLocalizedPattern());
        dcFromtDate.setDate(date);

        dcToDate.setDateFormatString(dateFormat.toLocalizedPattern());
        dcToDate.setDate(date);

        model = (DefaultTableModel) tblJob.getModel();

        txtDicountAcount.setEnabled(false);
        txtDiscountRate.setEnabled(false);
        lblDiscountAmount.setEnabled(false);
        lblDiscountRate.setEnabled(false);
        checkDiscountAmount.setEnabled(false);
        lblPresentage.setEnabled(false);
        checkDiscountRate.setEnabled(false);
        lblButnCalculate.setEnabled(false);
        checkDiscountAmount.setSelected(true);

        txtSubTotal.setText("0.0");
        txtDiscount.setText("0.0");
        txtNet.setText("0.0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelClientSearch = new javax.swing.JPanel();
        lblClientName = new javax.swing.JLabel();
        txtClientName = new javax.swing.JTextField();
        lblClientCode = new javax.swing.JLabel();
        txtClientCode = new javax.swing.JTextField();
        lblNo = new javax.swing.JLabel();
        txtContactPerson = new javax.swing.JTextField();
        lblStreet = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblStreet1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblSearchButn = new javax.swing.JLabel();
        panelItemInfor = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblProductCategory = new javax.swing.JLabel();
        comProductCategory = new javax.swing.JComboBox<>();
        txtDescription = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        comArea = new javax.swing.JComboBox<>();
        lblUnits = new javax.swing.JLabel();
        spUnits = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        lblFromDate = new javax.swing.JLabel();
        dcFromtDate = new com.toedter.calendar.JDateChooser();
        lblToDate = new javax.swing.JLabel();
        dcToDate = new com.toedter.calendar.JDateChooser();
        lblAddRowButn = new javax.swing.JLabel();
        checkDiscount = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblFrameName = new javax.swing.JLabel();
        lblHeadBanner = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        lblBackButtn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJob = new javax.swing.JTable();
        butnSave = new javax.swing.JLabel();
        lblSave = new javax.swing.JLabel();
        lblRefresh = new javax.swing.JLabel();
        butnRefresh = new javax.swing.JLabel();
        lblHom = new javax.swing.JLabel();
        butnHome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtJobId = new javax.swing.JTextField();
        lblJobId = new javax.swing.JLabel();
        txtTaxNo = new javax.swing.JTextField();
        lblJobId1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        dcJobDate = new com.toedter.calendar.JDateChooser();
        lblJobId2 = new javax.swing.JLabel();
        txtBillingMonth = new javax.swing.JTextField();
        panelJobTotal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        txtDiscount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNet = new javax.swing.JTextField();
        panelDiscount = new javax.swing.JPanel();
        lblDiscountAmount = new javax.swing.JLabel();
        txtDicountAcount = new javax.swing.JTextField();
        txtDiscountRate = new javax.swing.JTextField();
        lblDiscountRate = new javax.swing.JLabel();
        checkDiscountAmount = new javax.swing.JCheckBox();
        checkDiscountRate = new javax.swing.JCheckBox();
        lblPresentage = new javax.swing.JLabel();
        lblButnCalculate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelClientSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search Client", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        panelClientSearch.setOpaque(false);
        panelClientSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClientName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblClientName.setText("Client Name");
        panelClientSearch.add(lblClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 30));

        txtClientName.setBackground(new java.awt.Color(235, 245, 241));
        txtClientName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtClientName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClientNameKeyPressed(evt);
            }
        });
        panelClientSearch.add(txtClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 280, 30));

        lblClientCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblClientCode.setText("Client Code");
        panelClientSearch.add(lblClientCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 30));

        txtClientCode.setBackground(new java.awt.Color(235, 245, 241));
        txtClientCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtClientCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientCodeActionPerformed(evt);
            }
        });
        panelClientSearch.add(txtClientCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 110, 30));

        lblNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNo.setText("Contact Person");
        panelClientSearch.add(lblNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 30));

        txtContactPerson.setEditable(false);
        txtContactPerson.setBackground(new java.awt.Color(235, 245, 241));
        txtContactPerson.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelClientSearch.add(txtContactPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 280, 30));

        lblStreet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStreet.setText("Address");
        panelClientSearch.add(lblStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 110, 30));

        txtContactNo.setEditable(false);
        txtContactNo.setBackground(new java.awt.Color(235, 245, 241));
        txtContactNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelClientSearch.add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 280, 30));

        txtAddress.setEditable(false);
        txtAddress.setBackground(new java.awt.Color(235, 245, 241));
        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtAddress.setRows(5);
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(txtAddress);

        panelClientSearch.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 390, 150));

        lblStreet1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStreet1.setText("Contact No");
        panelClientSearch.add(lblStreet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelClientSearch.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 30, 190));

        lblSearchButn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-butn.png"))); // NOI18N
        lblSearchButn.setText("Search");
        lblSearchButn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSearchButnMousePressed(evt);
            }
        });
        panelClientSearch.add(lblSearchButn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 100, 50));

        jPanel1.add(panelClientSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 870, 240));

        panelItemInfor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelItemInfor.setOpaque(false);
        panelItemInfor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Description");
        panelItemInfor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 30));

        lblProductCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblProductCategory.setText("Product Category");
        panelItemInfor.add(lblProductCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 30));

        comProductCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "******** SELECT CATEGORY ********", "Plastic", "Glass", "Apparel", "Confectionary", " " }));
        panelItemInfor.add(comProductCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 320, 30));

        txtDescription.setBackground(new java.awt.Color(235, 245, 241));
        txtDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelItemInfor.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 630, 30));

        lblArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblArea.setText("Squre Feet Area");
        panelItemInfor.add(lblArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 30));

        comArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "***** SELECT *****", "500.00", "1000.00" }));
        panelItemInfor.add(comArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 160, 30));

        lblUnits.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUnits.setText("Units");
        panelItemInfor.add(lblUnits, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 50, 30));

        spUnits.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        panelItemInfor.add(spUnits, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 70, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelItemInfor.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 30, 180));

        lblFromDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFromDate.setText("From  Date");
        panelItemInfor.add(lblFromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 90, 30));
        panelItemInfor.add(dcFromtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 170, 30));

        lblToDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblToDate.setText("To Date");
        panelItemInfor.add(lblToDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 50, 30));
        panelItemInfor.add(dcToDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 170, 30));

        lblAddRowButn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddRowButn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add_row.png"))); // NOI18N
        lblAddRowButn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAddRowButnMousePressed(evt);
            }
        });
        panelItemInfor.add(lblAddRowButn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 90, 50));

        checkDiscount.setText("Discount");
        checkDiscount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkDiscount.setOpaque(false);
        checkDiscount.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkDiscountItemStateChanged(evt);
            }
        });
        panelItemInfor.add(checkDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 90, 30));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Add Row");
        panelItemInfor.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 90, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelItemInfor.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 30, 110));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove-row.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        panelItemInfor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 90, 40));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Remove Row");
        panelItemInfor.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 90, -1));

        jPanel1.add(panelItemInfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 930, 210));

        lblFrameName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFrameName.setForeground(new java.awt.Color(255, 255, 255));
        lblFrameName.setText("New Job");
        jPanel1.add(lblFrameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 370, 40));

        lblHeadBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main-pic.jpg"))); // NOI18N
        jPanel1.add(lblHeadBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 40, 1360, 110));

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBackButtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit-butn-small.png"))); // NOI18N
        lblBackButtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBackButtnMousePressed(evt);
            }
        });
        panelHeader.add(lblBackButtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 40, 40));

        jPanel1.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 40));

        tblJob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Category", "Description", "Sq. Ft. Area", "Rate", "No of Units", "From Date", "To Date", "No of Days", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblJob.setRowHeight(20);
        tblJob.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tblJob);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 1220, 120));

        butnSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        butnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save-butn.png"))); // NOI18N
        butnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butnSaveMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butnSaveMousePressed(evt);
            }
        });
        jPanel1.add(butnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 800, 70, 70));

        lblSave.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave.setText("Save");
        jPanel1.add(lblSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 880, 70, -1));

        lblRefresh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRefresh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRefresh.setText("Refresh");
        jPanel1.add(lblRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 880, 70, -1));

        butnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh-butn.png"))); // NOI18N
        butnRefresh.setText("Refresh");
        butnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butnRefreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butnRefreshMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butnRefreshMousePressed(evt);
            }
        });
        jPanel1.add(butnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 800, 70, 70));

        lblHom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblHom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHom.setText("Home");
        jPanel1.add(lblHom, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 880, 70, -1));

        butnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        butnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-butn.png"))); // NOI18N
        butnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butnHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butnHomeMousePressed(evt);
            }
        });
        jPanel1.add(butnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 800, 70, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Company Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtJobId.setBackground(new java.awt.Color(235, 245, 241));
        txtJobId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtJobId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtJobId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 100, 30));

        lblJobId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblJobId.setText("Billing Month");
        jPanel2.add(lblJobId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, 30));

        txtTaxNo.setBackground(new java.awt.Color(235, 245, 241));
        txtTaxNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtTaxNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 180, 30));

        lblJobId1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblJobId1.setText("Job ID");
        jPanel2.add(lblJobId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 30));

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDate.setText("JOb Date");
        jPanel2.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, 30));
        jPanel2.add(dcJobDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 180, 30));

        lblJobId2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblJobId2.setText("TAX No");
        jPanel2.add(lblJobId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, 30));

        txtBillingMonth.setBackground(new java.awt.Color(235, 245, 241));
        txtBillingMonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtBillingMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 180, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 330, 240));

        panelJobTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelJobTotal.setOpaque(false);
        panelJobTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Discournt");
        panelJobTotal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, 30));

        txtSubTotal.setEditable(false);
        txtSubTotal.setBackground(new java.awt.Color(235, 245, 241));
        txtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelJobTotal.add(txtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 150, 30));

        txtDiscount.setEditable(false);
        txtDiscount.setBackground(new java.awt.Color(235, 245, 241));
        txtDiscount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDiscount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDiscount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelJobTotal.add(txtDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 150, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Sub Total");
        panelJobTotal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Net");
        panelJobTotal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 80, 30));

        txtNet.setEditable(false);
        txtNet.setBackground(new java.awt.Color(235, 245, 241));
        txtNet.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNet.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelJobTotal.add(txtNet, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 150, 30));

        jPanel1.add(panelJobTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 560, 280, 210));

        panelDiscount.setBackground(new java.awt.Color(255, 255, 255));
        panelDiscount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDiscount.setOpaque(false);
        panelDiscount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDiscountAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDiscountAmount.setText("Discount Amount ");
        panelDiscount.add(lblDiscountAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        txtDicountAcount.setBackground(new java.awt.Color(235, 245, 241));
        txtDicountAcount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDicountAcount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDicountAcountKeyTyped(evt);
            }
        });
        panelDiscount.add(txtDicountAcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 150, 30));

        txtDiscountRate.setBackground(new java.awt.Color(235, 245, 241));
        txtDiscountRate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDiscountRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiscountRateKeyTyped(evt);
            }
        });
        panelDiscount.add(txtDiscountRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 110, 30));

        lblDiscountRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDiscountRate.setText("Discount Rate");
        panelDiscount.add(lblDiscountRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        buttonGroup1.add(checkDiscountAmount);
        checkDiscountAmount.setOpaque(false);
        checkDiscountAmount.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkDiscountAmountItemStateChanged(evt);
            }
        });
        panelDiscount.add(checkDiscountAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 30, 30));

        buttonGroup1.add(checkDiscountRate);
        checkDiscountRate.setOpaque(false);
        checkDiscountRate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkDiscountRateItemStateChanged(evt);
            }
        });
        panelDiscount.add(checkDiscountRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 30, 30));

        lblPresentage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPresentage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPresentage.setText("%");
        panelDiscount.add(lblPresentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 30, 30));

        lblButnCalculate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblButnCalculate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calclulat-icon.png"))); // NOI18N
        lblButnCalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblButnCalculateMousePressed(evt);
            }
        });
        panelDiscount.add(lblButnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 70, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Calculate");
        panelDiscount.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 70, -1));

        jPanel1.add(panelDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 790, 490, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 920));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackButtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackButtnMousePressed
        this.dispose();
    }//GEN-LAST:event_lblBackButtnMousePressed

    private void txtJobIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobIdActionPerformed

    private void butnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnHomeMousePressed

        this.setAlwaysOnTop(false);
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want go to home ?", "Message", JOptionPane.YES_NO_OPTION) == 0) {
            Home home = new Home(userRole);
            home.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_butnHomeMousePressed

    private void txtClientCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientCodeActionPerformed

        searchByClientCode();
    }//GEN-LAST:event_txtClientCodeActionPerformed

    private void lblSearchButnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchButnMousePressed

        searchByClientCode();

    }//GEN-LAST:event_lblSearchButnMousePressed

    private void butnSaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnSaveMousePressed

        if (JOptionPane.showConfirmDialog(null, "Are you sure you want save new job ?", "Message", JOptionPane.YES_NO_OPTION) == 0) {

            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Item details are empty.", "Empty Taable", JOptionPane.WARNING_MESSAGE);
            } else {

                String jobID = txtJobId.getText();
                String cientCode = txtClientCode.getText();
                String jobDate = dateFormat.format(dcJobDate.getDate());
                String billingMonth = txtBillingMonth.getText();
                String taxNo = txtTaxNo.getText();
                double subTotalVal = Double.parseDouble(txtSubTotal.getText());
                double discount = Double.parseDouble(txtDiscount.getText());
                double netTotal = Double.parseDouble(txtNet.getText());
                int jobStatus = 1;

                Job job = new Job(jobID, cientCode, jobDate, billingMonth, taxNo, subTotalVal, discount, netTotal, jobStatus);
                DBManager dbManager = new DBManager();

                boolean flag = dbManager.InsertNewJob(job);

                if (flag) {

                    int rowCount = 0;

                    for (int count = 0; count < model.getRowCount(); count++) {

                        String productType = model.getValueAt(count, 0).toString();
                        String productDesc = model.getValueAt(count, 1).toString();
                        double sqFeetArea = Double.parseDouble(model.getValueAt(count, 2).toString());
                        double rate = Double.parseDouble(model.getValueAt(count, 3).toString());
                        int units = Integer.parseInt(model.getValueAt(count, 4).toString());
                        String fromDate = model.getValueAt(count, 5).toString();
                        String toDate = model.getValueAt(count, 6).toString();
                        int days = Integer.parseInt(model.getValueAt(count, 7).toString());
                        double itemTotal = Double.parseDouble(model.getValueAt(count, 8).toString());

                        Job itemJob = new Job(jobID, productType, productDesc, sqFeetArea, units, rate, fromDate, toDate, days, itemTotal);
                        DBManager itemDBManager = new DBManager();
                        itemDBManager.insertNewItem(itemJob);

                        rowCount++;
                    }

                    if (rowCount == model.getRowCount()) {

                        JOptionPane.showMessageDialog(null, "Storage job insert successfully.");
                        //  cllearFields();

                        if (JOptionPane.showConfirmDialog(null, "You want to preview invoice?", "Information", JOptionPane.YES_NO_OPTION) == 0) {

                            Invoice invoice = new Invoice();

                            invoice.setJobId(job.getJobId());

                            ViewInvoice viewInvoice = new ViewInvoice(invoice);
                            viewInvoice.setVisible(true);
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Insert Fail.", "Error!", JOptionPane.ERROR_MESSAGE);
                    }

                }

            }
        }

    }//GEN-LAST:event_butnSaveMousePressed

    private void lblAddRowButnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddRowButnMousePressed

        if (comProductCategory.getSelectedItem().equals("******** SELECT CATEGORY ********")) {
            JOptionPane.showMessageDialog(null, "Can't add item details. Product category is invalid", "Invalid", JOptionPane.WARNING_MESSAGE);
        } else if (comArea.getSelectedItem().equals("***** SELECT *****")) {
            JOptionPane.showMessageDialog(null, "Can't add item details. invalid squre feet area", "Invalid", JOptionPane.WARNING_MESSAGE);
        } else {

            DBManager dBManager = new DBManager();

            int numberOfDays = dBManager.getNumberOfDays((int) dcFromtDate.getDate().getTime(), (int) dcToDate.getDate().getTime());

            double rate = dBManager.getSqFtArea(Double.parseDouble(comArea.getSelectedItem().toString()));

            int units = (int) spUnits.getValue();

            double unitTotal = rate * units * numberOfDays;

            subTotal += unitTotal;
            txtSubTotal.setText(subTotal + "");

            Object colum[] = new Object[9];

            colum[0] = txtDescription.getText();
            colum[1] = comProductCategory.getSelectedItem();
            colum[2] = comArea.getSelectedItem();
            colum[3] = rate;
            colum[4] = units;
            colum[5] = dateFormat.format(dcFromtDate.getDate());
            colum[6] = dateFormat.format(dcToDate.getDate());
            colum[7] = numberOfDays;
            colum[8] = unitTotal;

            model.addRow(colum);

            txtDescription.setText("");
            comProductCategory.setSelectedItem("******** SELECT CATEGORY ********");
            comArea.setSelectedItem("***** SELECT *****");
            spUnits.setValue(1);
            dcFromtDate.setDate(date);
            dcToDate.setDate(date);
        }
    }//GEN-LAST:event_lblAddRowButnMousePressed

    private void butnRefreshMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnRefreshMousePressed

        cllearFields();

    }//GEN-LAST:event_butnRefreshMousePressed

    private void butnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnSaveMouseEntered
        butnSave.setBounds(930, 800, 70, 70);
    }//GEN-LAST:event_butnSaveMouseEntered

    private void butnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnSaveMouseExited
        butnSave.setBounds(930, 805, 70, 70);
    }//GEN-LAST:event_butnSaveMouseExited

    private void butnRefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnRefreshMouseEntered
        butnRefresh.setBounds(1050, 800, 70, 70);
    }//GEN-LAST:event_butnRefreshMouseEntered

    private void butnRefreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnRefreshMouseExited
        butnRefresh.setBounds(1050, 805, 70, 70);
    }//GEN-LAST:event_butnRefreshMouseExited

    private void butnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnHomeMouseEntered
        butnHome.setBounds(1170, 800, 70, 70);
    }//GEN-LAST:event_butnHomeMouseEntered

    private void butnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnHomeMouseExited
        butnHome.setBounds(1170, 805, 70, 70);
    }//GEN-LAST:event_butnHomeMouseExited

    private void txtClientNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClientNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            new ClientSearch(this) {
                public boolean close() {
                    this.dispose();
                    return false;
                }
            }.setVisible(true);

        }
    }//GEN-LAST:event_txtClientNameKeyPressed

    private void checkDiscountItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkDiscountItemStateChanged

        if (checkDiscount.isSelected()) {
            txtDicountAcount.setEnabled(true);
            txtDiscountRate.setEnabled(true);
            checkDiscountAmount.setEnabled(true);
            checkDiscountRate.setEnabled(true);
            lblButnCalculate.setEnabled(true);
            lblDiscountAmount.setEnabled(true);
            lblDiscountRate.setEnabled(true);
            checkDiscountAmount.setEnabled(true);
            lblPresentage.setEnabled(true);
            checkDiscountAmount.setSelected(true);
        } else {
            txtDicountAcount.setEnabled(false);
            txtDiscountRate.setEnabled(false);
            checkDiscountAmount.setEnabled(false);
            checkDiscountRate.setEnabled(false);
            lblButnCalculate.setEnabled(false);
            lblDiscountAmount.setEnabled(false);
            lblDiscountRate.setEnabled(false);
            checkDiscountAmount.setEnabled(false);
            lblPresentage.setEnabled(false);
        }
    }//GEN-LAST:event_checkDiscountItemStateChanged

    private void txtDicountAcountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDicountAcountKeyTyped
        DBManager.textFieldNumberOnly(evt);
    }//GEN-LAST:event_txtDicountAcountKeyTyped

    private void txtDiscountRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscountRateKeyTyped
        DBManager.textFieldNumberOnly(evt);
    }//GEN-LAST:event_txtDiscountRateKeyTyped

    private void lblButnCalculateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblButnCalculateMousePressed

        if (checkDiscountAmount.isSelected() || checkDiscountRate.isSelected()) {

            double discountAmount = 0.0, netAmount = 0.0, subTotalVal = 0.0, discountRate = 0.0;

            subTotalVal = Double.parseDouble(txtSubTotal.getText());

            if (checkDiscountAmount.isSelected() && !txtDicountAcount.getText().isEmpty()) {

                discountAmount = Double.parseDouble(txtDicountAcount.getText());
                netAmount = subTotalVal - discountAmount;

            } else if (checkDiscountRate.isSelected() && !txtDiscountRate.getText().isEmpty()) {

                discountRate = Double.parseDouble(txtDiscountRate.getText());

                discountAmount = (subTotalVal * discountRate) / 100;
                netAmount = subTotalVal - discountAmount;

            }

            txtDiscount.setText(discountAmount + "");
            txtNet.setText(netAmount + "");
        }

    }//GEN-LAST:event_lblButnCalculateMousePressed

    private void checkDiscountAmountItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkDiscountAmountItemStateChanged

        if (checkDiscountAmount.isSelected()) {
            txtDiscountRate.setText("");
            txtDiscount.setText("0.0");
            txtNet.setText("0.0");
        }
    }//GEN-LAST:event_checkDiscountAmountItemStateChanged

    private void checkDiscountRateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkDiscountRateItemStateChanged

        if (checkDiscountRate.isSelected()) {
            txtDicountAcount.setText("");
            txtDiscount.setText("0.0");
            txtNet.setText("0.0");
        }
    }//GEN-LAST:event_checkDiscountRateItemStateChanged

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed

        subTotal = 0.0;
        if (tblJob.getRowCount() > 0) {

            if (tblJob.getSelectedRow() != -1) {

                model.removeRow(tblJob.getSelectedRow());

                for (int i = 0; i < tblJob.getRowCount(); i++) {
                    subTotal += Double.parseDouble(tblJob.getValueAt(i, 8).toString());
                }
            }
        }

        if (tblJob.getRowCount() == 0) {
            txtSubTotal.setText("0.0");
            txtDiscount.setText("0.0");
            txtNet.setText("0.0");
        } else {

            txtSubTotal.setText(subTotal + "");
        }
    }//GEN-LAST:event_jLabel3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel butnHome;
    private javax.swing.JLabel butnRefresh;
    private javax.swing.JLabel butnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkDiscount;
    private javax.swing.JCheckBox checkDiscountAmount;
    private javax.swing.JCheckBox checkDiscountRate;
    private javax.swing.JComboBox<String> comArea;
    private javax.swing.JComboBox<String> comProductCategory;
    private com.toedter.calendar.JDateChooser dcFromtDate;
    private com.toedter.calendar.JDateChooser dcJobDate;
    private com.toedter.calendar.JDateChooser dcToDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAddRowButn;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblBackButtn;
    private javax.swing.JLabel lblButnCalculate;
    private javax.swing.JLabel lblClientCode;
    private javax.swing.JLabel lblClientName;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDiscountAmount;
    private javax.swing.JLabel lblDiscountRate;
    private javax.swing.JLabel lblFrameName;
    private javax.swing.JLabel lblFromDate;
    private javax.swing.JLabel lblHeadBanner;
    private javax.swing.JLabel lblHom;
    private javax.swing.JLabel lblJobId;
    private javax.swing.JLabel lblJobId1;
    private javax.swing.JLabel lblJobId2;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblPresentage;
    private javax.swing.JLabel lblProductCategory;
    private javax.swing.JLabel lblRefresh;
    private javax.swing.JLabel lblSave;
    private javax.swing.JLabel lblSearchButn;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblStreet1;
    private javax.swing.JLabel lblToDate;
    private javax.swing.JLabel lblUnits;
    private javax.swing.JPanel panelClientSearch;
    private javax.swing.JPanel panelDiscount;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelItemInfor;
    private javax.swing.JPanel panelJobTotal;
    private javax.swing.JSpinner spUnits;
    private javax.swing.JTable tblJob;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtBillingMonth;
    private javax.swing.JTextField txtClientCode;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtContactPerson;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtDicountAcount;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtDiscountRate;
    private javax.swing.JTextField txtJobId;
    private javax.swing.JTextField txtNet;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTaxNo;
    // End of variables declaration//GEN-END:variables

    private void searchByClientCode() {

        if (!txtClientCode.getText().isEmpty()) {

            String clientCode = txtClientCode.getText();
            Client client = new Client();
            client.setClientCode(clientCode);

            DBManager dbManager = new DBManager();
            client = dbManager.searchClientByClientCode(client);

            if (client == null) {

                JOptionPane.showMessageDialog(null, "Invalid Client Code.", "Invalid", JOptionPane.WARNING_MESSAGE);
            } else {

                txtClientCode.setText(client.getClientCode());
                txtClientName.setText(client.getClientName());
                txtContactPerson.setText(client.getFirstName() + " " + client.getLastName());
                txtContactNo.setText(client.getMobileNo());
                txtAddress.setText(client.getNo() + "\n" + client.getStreet() + "\n" + client.getCity());
            }
        }
    }

    void searchClientByClientName(String clientName) {

        Client client = new Client(clientName);
        DBManager dbManager = new DBManager();
        client = dbManager.searchClientByClientName(client);

        if (client == null) {

            JOptionPane.showMessageDialog(null, "No client record found.", "No Record", JOptionPane.WARNING_MESSAGE);
        } else {

            txtClientCode.setText(client.getClientCode());
            txtClientName.setText(client.getClientName());
            txtContactPerson.setText(client.getFirstName() + " " + client.getLastName());
            txtContactNo.setText(client.getMobileNo());
            txtAddress.setText(client.getNo() + "\n" + client.getStreet() + "\n" + client.getCity());
        }
    }

//   private void getNewJobID() {
//
//        DBManager dbManager = new DBManager();
//
//        String newClientCode = dbManager.getNewClientCode();
//
//        lblValueClientCode.setText(newClientCode);
//    }
    private void cllearFields() {

        txtJobId.setText("");
        txtTaxNo.setText("");
        txtBillingMonth.setText("");
        txtClientCode.setText("");
        txtClientName.setText("");
        txtContactPerson.setText("");
        txtContactNo.setText("");
        txtAddress.setText("");
        model.setRowCount(0);
        txtDescription.setText("");
        comProductCategory.setSelectedItem("******** SELECT CATEGORY ********");
        comArea.setSelectedItem("***** SELECT *****");
        spUnits.setValue(0);
        txtSubTotal.setText("0.0");
        txtDiscount.setText("0.0");
        txtNet.setText("0.0");
        dcJobDate.setDate(date);
        dcFromtDate.setDate(date);
        dcToDate.setDate(date);
    }

}
