/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controler.DBManager.userRole;
import Controler.DBManager;
import Model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Gihan
 */
public class RegisterUser extends javax.swing.JFrame {

    /**
     * Creates new form CreateUser
     */
    public RegisterUser() {
        initComponents();

        AllMarkUnvisible();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBack = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblBackButtn = new javax.swing.JLabel();
        lblFrameName = new javax.swing.JLabel();
        lblHeadBanner = new javax.swing.JLabel();
        lblEmpNo = new javax.swing.JLabel();
        txtEmpNo = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblMobileNo = new javax.swing.JLabel();
        txtMobileNo = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblUserRole = new javax.swing.JLabel();
        comUserRole = new javax.swing.JComboBox<>();
        lblConfirm = new javax.swing.JLabel();
        txtConfirm = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        butnHome = new javax.swing.JLabel();
        butnSave = new javax.swing.JLabel();
        lblHom = new javax.swing.JLabel();
        butnRefresh = new javax.swing.JLabel();
        lblSave = new javax.swing.JLabel();
        lblRefresh = new javax.swing.JLabel();
        lblCrossMark = new javax.swing.JLabel();
        lblCrossMark1 = new javax.swing.JLabel();
        lblCheckMark = new javax.swing.JLabel();
        lblCheckMark1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBack.setBackground(new java.awt.Color(255, 255, 255));
        panelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBackButtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit-butn-small.png"))); // NOI18N
        lblBackButtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBackButtnMousePressed(evt);
            }
        });
        panelHeader.add(lblBackButtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 40, 40));

        panelBack.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 40));

        lblFrameName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFrameName.setForeground(new java.awt.Color(255, 255, 255));
        lblFrameName.setText("Create New User");
        panelBack.add(lblFrameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 370, 40));

        lblHeadBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main-pic.jpg"))); // NOI18N
        panelBack.add(lblHeadBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 40, 1370, 110));

        lblEmpNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmpNo.setText("Employee No.");
        panelBack.add(lblEmpNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, 30));

        txtEmpNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmpNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBack.add(txtEmpNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 140, 30));

        lblFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFirstName.setText("First Name");
        panelBack.add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 90, 30));

        txtFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyTyped(evt);
            }
        });
        panelBack.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 250, 30));

        lblLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLastName.setText("Last Name");
        panelBack.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 90, 30));

        txtLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastNameKeyTyped(evt);
            }
        });
        panelBack.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 250, 30));

        lblMobileNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMobileNo.setText("Mobile Number");
        panelBack.add(lblMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 90, 30));

        txtMobileNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMobileNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMobileNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMobileNoFocusLost(evt);
            }
        });
        txtMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobileNoKeyTyped(evt);
            }
        });
        panelBack.add(txtMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 250, 30));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("Email");
        panelBack.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 90, 30));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        panelBack.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 250, 30));

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUserName.setText("User Name");
        panelBack.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 90, 30));

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBack.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 250, 30));

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPassword.setText("Password");
        panelBack.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 70, 30));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
        });
        panelBack.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 250, 30));

        lblUserRole.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUserRole.setText("User Role");
        panelBack.add(lblUserRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 90, 30));

        comUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "******* User Role *******", "Manager", "Operator", " " }));
        panelBack.add(comUserRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 250, 30));

        lblConfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConfirm.setText("Confirm");
        panelBack.add(lblConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 60, 30));

        txtConfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtConfirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmFocusGained(evt);
            }
        });
        panelBack.add(txtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 250, 30));
        panelBack.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 350, 20));

        butnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        butnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-butn.png"))); // NOI18N
        butnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butnHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butnHomeMousePressed(evt);
            }
        });
        panelBack.add(butnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 70, 70));

        butnSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        butnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save-butn.png"))); // NOI18N
        butnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butnSaveMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butnSaveMousePressed(evt);
            }
        });
        panelBack.add(butnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 70, 70));

        lblHom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblHom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHom.setText("Home");
        panelBack.add(lblHom, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 600, 70, -1));

        butnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh-butn.png"))); // NOI18N
        butnRefresh.setText("Refresh");
        butnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butnRefreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butnRefreshMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butnRefreshMousePressed(evt);
            }
        });
        panelBack.add(butnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, 70, 70));

        lblSave.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave.setText("Save");
        panelBack.add(lblSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 600, 70, -1));

        lblRefresh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRefresh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRefresh.setText("Refresh");
        panelBack.add(lblRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 600, 70, -1));

        lblCrossMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross-mark.png"))); // NOI18N
        panelBack.add(lblCrossMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 40, 30));

        lblCrossMark1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross-mark.png"))); // NOI18N
        panelBack.add(lblCrossMark1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 40, 30));

        lblCheckMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check-mark.png"))); // NOI18N
        panelBack.add(lblCheckMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 40, 30));

        lblCheckMark1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check-mark.png"))); // NOI18N
        panelBack.add(lblCheckMark1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 40, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wave-pack.png"))); // NOI18N
        panelBack.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-450, 130, 1340, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back-pic1.png"))); // NOI18N
        panelBack.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 440, 490));

        getContentPane().add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackButtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackButtnMousePressed

        this.setAlwaysOnTop(false);
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to close?", "Warning", JOptionPane.YES_NO_OPTION) == 0) {

            this.dispose();
        }
    }//GEN-LAST:event_lblBackButtnMousePressed

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained

        this.lblCheckMark.setVisible(false);
        this.lblCrossMark.setVisible(false);
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmFocusGained

        this.lblCheckMark.setVisible(false);
        this.lblCrossMark.setVisible(false);
    }//GEN-LAST:event_txtConfirmFocusGained

    private void butnSaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnSaveMousePressed

        String empNo = txtEmpNo.getText();
        String fName = txtFirstName.getText();
        String lName = txtLastName.getText();
        String mobile = txtMobileNo.getText();
        String email = txtEmail.getText();
        String username = txtUserName.getText();
        String pass = txtPassword.getText();
        String userRole = (String) comUserRole.getSelectedItem();
        int status = 1;
        if (empNo.equals("")) {
            JOptionPane.showMessageDialog(null, "Employee ID can't be empty.", "Empty Field Error", JOptionPane.INFORMATION_MESSAGE);
        } else if (username.equals("") && pass.equals("")) {
            JOptionPane.showMessageDialog(null, "Username & password can't be empty.", "Empty Field Error", JOptionPane.INFORMATION_MESSAGE);
        } else if (userRole.equals("******* User Role *******")) {
            JOptionPane.showMessageDialog(null, "User role is invalid.", "Invalid", JOptionPane.INFORMATION_MESSAGE);
        } else if (!pass.equals(txtConfirm.getText())) {
            AllMarkUnvisible();
            CrossMarkVisible();
            JOptionPane.showMessageDialog(null, "Those passwords didn’t match. Try again.", "Mismatch Error", JOptionPane.WARNING_MESSAGE);
        } else {

            AllMarkUnvisible();
            CheckMarkVisible();

            DBManager dbManager = new DBManager();
            
            User checkUser = new User(empNo);

            boolean checkExsistence = dbManager.checkUserExistence(checkUser);

            if (checkExsistence) {
                JOptionPane.showMessageDialog(null, "Can't save the user information. ( " + empNo + " ) This employee number is aready existing.", "Error!", JOptionPane.WARNING_MESSAGE);
            } else {

                User user = new User(empNo, fName, lName, mobile, email, username, pass, userRole, status);

                boolean flag = dbManager.insertNewUser(user);
                if (flag) {
                    JOptionPane.showMessageDialog(null, "User successfully inserted.", "Sucees", JOptionPane.INFORMATION_MESSAGE);
                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(null, "User insert fail.", "Error!", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_butnSaveMousePressed

    private void butnRefreshMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnRefreshMousePressed
        if (JOptionPane.showConfirmDialog(null, "Are you sure to clear the fields ?", "Message", JOptionPane.YES_NO_OPTION) == 0) {
            clearFields();
        }
    }//GEN-LAST:event_butnRefreshMousePressed

    private void butnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnHomeMousePressed

        if (JOptionPane.showConfirmDialog(null, "Are you sure you want go to home ?", "Message", JOptionPane.YES_NO_OPTION) == 0) {
            Home home = new Home(userRole);
            home.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_butnHomeMousePressed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost

        if (!txtEmail.getText().isEmpty()) {

            boolean flag = DBManager.textFieldEmailAddress(txtEmail.getText());
            if (flag) {
                txtPassword.grabFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Email address is invalid.", "Invalid", 2);
                txtEmail.grabFocus();
            }
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void butnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnSaveMouseEntered
        butnSave.setBounds(610, 525, 70, 70);
    }//GEN-LAST:event_butnSaveMouseEntered

    private void butnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnSaveMouseExited
        butnSave.setBounds(610, 520, 70, 70);
    }//GEN-LAST:event_butnSaveMouseExited

    private void butnRefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnRefreshMouseEntered
        butnRefresh.setBounds(730, 525, 70, 70);
    }//GEN-LAST:event_butnRefreshMouseEntered

    private void butnRefreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnRefreshMouseExited
        butnRefresh.setBounds(730, 520, 70, 70);
    }//GEN-LAST:event_butnRefreshMouseExited

    private void butnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnHomeMouseEntered
        butnHome.setBounds(850, 525, 70, 70);
    }//GEN-LAST:event_butnHomeMouseEntered

    private void butnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnHomeMouseExited
        butnHome.setBounds(850, 520, 70, 70);
    }//GEN-LAST:event_butnHomeMouseExited

    private void txtMobileNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMobileNoFocusLost

        if (!txtMobileNo.getText().isEmpty()) {

            boolean flag = DBManager.textFieldTelephoneNumber(txtMobileNo.getText());
            if (flag) {
                txtUserName.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Mobile Number is invalid.", "Invalid", 2);
                txtMobileNo.grabFocus();
            }
        }
    }//GEN-LAST:event_txtMobileNoFocusLost

    private void txtFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyTyped
       
        DBManager.textFieldLettersOnly(evt);
    }//GEN-LAST:event_txtFirstNameKeyTyped

    private void txtLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyTyped
        DBManager.textFieldLettersOnly(evt);
    }//GEN-LAST:event_txtLastNameKeyTyped

    private void txtMobileNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileNoKeyTyped
       DBManager.textFieldNumberOnly(evt);
    }//GEN-LAST:event_txtMobileNoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RegisterUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel butnHome;
    private javax.swing.JLabel butnRefresh;
    private javax.swing.JLabel butnSave;
    private javax.swing.JComboBox<String> comUserRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBackButtn;
    private javax.swing.JLabel lblCheckMark;
    private javax.swing.JLabel lblCheckMark1;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblCrossMark;
    private javax.swing.JLabel lblCrossMark1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpNo;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFrameName;
    private javax.swing.JLabel lblHeadBanner;
    private javax.swing.JLabel lblHom;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMobileNo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRefresh;
    private javax.swing.JLabel lblSave;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserRole;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField txtConfirm;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpNo;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void CheckMarkVisible() {
        this.lblCheckMark.setVisible(true);
        this.lblCheckMark1.setVisible(true);
    }

    private void CrossMarkVisible() {
        this.lblCrossMark.setVisible(true);
        this.lblCrossMark1.setVisible(true);
    }

    private void AllMarkUnvisible() {
        this.lblCheckMark.setVisible(false);
        this.lblCrossMark.setVisible(false);
        this.lblCheckMark1.setVisible(false);
        this.lblCrossMark1.setVisible(false);
    }

    private void clearFields() {
        txtEmpNo.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtMobileNo.setText("");
        txtEmail.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
        txtConfirm.setText("");
        comUserRole.setSelectedItem("******* User Role *******");
        AllMarkUnvisible();
    }
}
