/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controler.DBManager.userRole;
import static Controler.DBManager.userName;
import Controler.DBManager;
import Model.Client;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Gihan
 */
public class RegisterClient extends javax.swing.JFrame {

    /**
     * Creates new form RegisterClient
     */
    Date systemDate;
    SimpleDateFormat dateFormat;

    public RegisterClient() {
        initComponents();

        systemDate = new Date();
        dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        getNewClientCode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblBackButtn = new javax.swing.JLabel();
        lblFrameName = new javax.swing.JLabel();
        lblClientCode = new javax.swing.JLabel();
        lblValueClientCode = new javax.swing.JLabel();
        lblClientName = new javax.swing.JLabel();
        txtClientName = new javax.swing.JTextField();
        lblAddNo = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        lblStreet = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblContactNo = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        lblFax = new javax.swing.JLabel();
        txtFaxNo = new javax.swing.JTextField();
        lblContactPerson = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblMobile = new javax.swing.JLabel();
        txtMobileNo = new javax.swing.JTextField();
        lblSaveButtn = new javax.swing.JLabel();
        lblSave = new javax.swing.JLabel();
        lblRefreshButtn = new javax.swing.JLabel();
        lblRefresh = new javax.swing.JLabel();
        lblHomeButn = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblHeadBanner = new javax.swing.JLabel();
        back_1 = new javax.swing.JLabel();
        lblBackImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBackButtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit-butn-small.png"))); // NOI18N
        lblBackButtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBackButtnMousePressed(evt);
            }
        });
        panelHeader.add(lblBackButtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 40, 40));

        panelBackground.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 40));

        lblFrameName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFrameName.setForeground(new java.awt.Color(255, 255, 255));
        lblFrameName.setText("Register New Client");
        panelBackground.add(lblFrameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 370, 40));

        lblClientCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblClientCode.setText("Client Code");
        panelBackground.add(lblClientCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, 30));

        lblValueClientCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBackground.add(lblValueClientCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 150, 30));

        lblClientName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblClientName.setText("Client Name");
        panelBackground.add(lblClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 30));

        txtClientName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBackground.add(txtClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 790, 30));

        lblAddNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddNo.setText("Address No.");
        panelBackground.add(lblAddNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 90, 30));

        txtNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBackground.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 250, 30));

        lblStreet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStreet.setText("Street");
        panelBackground.add(lblStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 90, 30));

        txtStreet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBackground.add(txtStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 350, 30));

        lblCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCity.setText("City");
        panelBackground.add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 90, 30));

        txtCity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBackground.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 250, 30));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("Email ");
        panelBackground.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 90, 30));

        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        panelBackground.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 350, 30));

        lblContactNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblContactNo.setText("Contact No.");
        panelBackground.add(lblContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 90, 30));

        txtContactNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtContactNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContactNoFocusLost(evt);
            }
        });
        txtContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactNoKeyTyped(evt);
            }
        });
        panelBackground.add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 250, 30));

        lblFax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFax.setText("Fax");
        panelBackground.add(lblFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 90, 30));

        txtFaxNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBackground.add(txtFaxNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 350, 30));

        lblContactPerson.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblContactPerson.setText("Contact Person");
        panelBackground.add(lblContactPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 130, 30));
        panelBackground.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 130, 10));

        lblFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFirstName.setText("First Name");
        panelBackground.add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 90, 30));

        txtFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyTyped(evt);
            }
        });
        panelBackground.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 250, 30));

        lblLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLastName.setText("Last Name");
        panelBackground.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 90, 30));

        txtLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastNameKeyTyped(evt);
            }
        });
        panelBackground.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 350, 30));

        lblMobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMobile.setText("Mobile No.");
        panelBackground.add(lblMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 90, 30));

        txtMobileNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMobileNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMobileNoFocusLost(evt);
            }
        });
        txtMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobileNoKeyTyped(evt);
            }
        });
        panelBackground.add(txtMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 250, 30));

        lblSaveButtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaveButtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save-icon.png"))); // NOI18N
        lblSaveButtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSaveButtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSaveButtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSaveButtnMousePressed(evt);
            }
        });
        panelBackground.add(lblSaveButtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, 70, 70));

        lblSave.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave.setText("Save");
        panelBackground.add(lblSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, 70, 30));

        lblRefreshButtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRefreshButtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh-butn.png"))); // NOI18N
        lblRefreshButtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRefreshButtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRefreshButtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRefreshButtnMousePressed(evt);
            }
        });
        panelBackground.add(lblRefreshButtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 550, 70, 70));

        lblRefresh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRefresh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRefresh.setText("Refresh");
        panelBackground.add(lblRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 620, 70, 30));

        lblHomeButn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-butn.png"))); // NOI18N
        lblHomeButn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeButnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeButnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHomeButnMousePressed(evt);
            }
        });
        panelBackground.add(lblHomeButn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 70, 70));

        lblHome.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setText("Home");
        panelBackground.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 620, 70, 30));

        lblHeadBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main-pic.jpg"))); // NOI18N
        panelBackground.add(lblHeadBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, 40, 1360, 110));

        back_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wave-pack.png"))); // NOI18N
        panelBackground.add(back_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-520, 70, 1280, 440));

        lblBackImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wave-back3.png"))); // NOI18N
        panelBackground.add(lblBackImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 550, 620));

        getContentPane().add(panelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackButtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackButtnMousePressed
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Warning", JOptionPane.YES_NO_OPTION) == 0) {
            this.setAlwaysOnTop(false);
            this.dispose();
        }
    }//GEN-LAST:event_lblBackButtnMousePressed

    private void lblSaveButtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveButtnMousePressed

        if (JOptionPane.showConfirmDialog(null, "Are you sure you want save client ?", "Message", JOptionPane.YES_NO_OPTION) == 0) {

            String clientCode = lblValueClientCode.getText();
            String clientName = txtClientName.getText();
            String addressNo = txtNo.getText();
            String street = txtStreet.getText();
            String city = txtCity.getText();
            String email = txtEmail.getText();
            String fax = txtFaxNo.getText();
            String contactNo = txtContactNo.getText();
            String firstName = txtFirstName.getText();
            String latName = txtLastName.getText();
            String mobileNo = txtMobileNo.getText();
            String registerPerson = userName;
            String registerDate = dateFormat.format(systemDate);
            int clientStatus = 1;

            if (clientName.equals("")) {
                JOptionPane.showMessageDialog(null, "Client name can't be empty.", "Empty Field Error", JOptionPane.INFORMATION_MESSAGE);
            } else if (contactNo.equals("")) {
                JOptionPane.showMessageDialog(null, "Client Contact number can't be empty.", "Empty Field Error", JOptionPane.INFORMATION_MESSAGE);
            } else if ((firstName.isEmpty() || firstName.isEmpty()) && mobileNo.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Client Contact person information cant't be empty", "Invalid", JOptionPane.INFORMATION_MESSAGE);
            } else {

                Client client = new Client(clientCode, clientName, addressNo, street, city, email, fax, contactNo, firstName, latName, mobileNo, registerPerson, registerDate, clientStatus);
                boolean flag = DBManager.registerClient(client);

                if (flag) {
                    JOptionPane.showMessageDialog(null, "Client register successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(null, "User insert fail.", "Error!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_lblSaveButtnMousePressed

    private void lblRefreshButtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRefreshButtnMousePressed
        if (JOptionPane.showConfirmDialog(null, "Are you sure to clear the fields ?", "Message", JOptionPane.YES_NO_OPTION) == 0) {
            clearFields();
        }
    }//GEN-LAST:event_lblRefreshButtnMousePressed

    private void txtFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyTyped
        DBManager.textFieldLettersOnly(evt);
    }//GEN-LAST:event_txtFirstNameKeyTyped

    private void txtLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyTyped
        DBManager.textFieldLettersOnly(evt);
    }//GEN-LAST:event_txtLastNameKeyTyped

    private void txtMobileNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileNoKeyTyped
        DBManager.textFieldNumberOnly(evt);
    }//GEN-LAST:event_txtMobileNoKeyTyped

    private void txtContactNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContactNoFocusLost
        /*
        Check the mobile validation if the Contact number TextFiled is not empty
         */
        if (!txtContactNo.getText().isEmpty()) {

            boolean flag = DBManager.textFieldTelephoneNumber(txtContactNo.getText());
            if (flag) {
                txtFaxNo.grabFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Contact Number is invalid.", "Invalid", 2);
                txtContactNo.grabFocus();
            }
        }
    }//GEN-LAST:event_txtContactNoFocusLost

    private void txtMobileNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMobileNoFocusLost
        /*
        Check the mobile validation if the mobile number TextFiled is not empty
         */
        if (!txtMobileNo.getText().isEmpty()) {
            boolean flag = DBManager.textFieldTelephoneNumber(txtMobileNo.getText());
            if (flag) {
                txtFaxNo.setFocusable(false);
            } else {
                JOptionPane.showMessageDialog(null, "Contact Number is invalid.", "Invalid", 2);
                txtMobileNo.grabFocus();
            }
        }
    }//GEN-LAST:event_txtMobileNoFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        /*
        Check the email validation if the Email TextFiled is not empty
         */
        if (!txtEmail.getText().isEmpty()) {
            boolean flag = DBManager.textFieldEmailAddress(txtEmail.getText());
            if (flag) {
                txtFaxNo.grabFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Email address is invalid.", "Invalid", 2);
                txtEmail.grabFocus();
            }
        }

    }//GEN-LAST:event_txtEmailFocusLost

    private void lblHomeButnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeButnMousePressed

        this.setAlwaysOnTop(false);
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want go to home ?", "Message", JOptionPane.YES_NO_OPTION) == 0) {
            Home home = new Home(userRole);
            home.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lblHomeButnMousePressed

    private void lblSaveButtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveButtnMouseEntered
        lblSaveButtn.setBounds(610, 555, 70, 70);
    }//GEN-LAST:event_lblSaveButtnMouseEntered

    private void lblSaveButtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveButtnMouseExited
        lblSaveButtn.setBounds(610, 550, 70, 70);
    }//GEN-LAST:event_lblSaveButtnMouseExited

    private void lblRefreshButtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRefreshButtnMouseEntered
        lblRefreshButtn.setBounds(730, 555, 70, 70);
    }//GEN-LAST:event_lblRefreshButtnMouseEntered

    private void lblRefreshButtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRefreshButtnMouseExited
        lblRefreshButtn.setBounds(730, 550, 70, 70);
    }//GEN-LAST:event_lblRefreshButtnMouseExited

    private void lblHomeButnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeButnMouseEntered
        lblHomeButn.setBounds(850, 555, 70, 70);
    }//GEN-LAST:event_lblHomeButnMouseEntered

    private void lblHomeButnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeButnMouseExited
        lblHomeButn.setBounds(850, 550, 70, 70);
    }//GEN-LAST:event_lblHomeButnMouseExited

    private void txtContactNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNoKeyTyped
       DBManager.textFieldNumberOnly(evt);
    }//GEN-LAST:event_txtContactNoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RegisterClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAddNo;
    private javax.swing.JLabel lblBackButtn;
    private javax.swing.JLabel lblBackImg;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblClientCode;
    private javax.swing.JLabel lblClientName;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblContactPerson;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFrameName;
    private javax.swing.JLabel lblHeadBanner;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblHomeButn;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblRefresh;
    private javax.swing.JLabel lblRefreshButtn;
    private javax.swing.JLabel lblSave;
    private javax.swing.JLabel lblSaveButtn;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblValueClientCode;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNo;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtStreet;
    // End of variables declaration//GEN-END:variables

    private void getNewClientCode() {

        DBManager dbManager = new DBManager();

        String newClientCode = dbManager.getNewClientCode();

        lblValueClientCode.setText(newClientCode);
    }

    private void clearFields() {
        lblValueClientCode.setText("");
        txtClientName.setText("");
        txtNo.setText("");
        txtStreet.setText("");
        txtCity.setText("");
        txtEmail.setText("");
        txtFaxNo.setText("");
        txtContactNo.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtMobileNo.setText("");
        getNewClientCode();
    }
}
